//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
[XmlRoot("processes")]
public partial class processes {
    
    private processesProcess[] processField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("process")]
    public processesProcess[] process {
        get {
            return this.processField;
        }
        set {
            this.processField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class processesProcess {
    
    private string processIdField;
    
    private string processRadNumberField;
    
    private processesProcessSavedMessage savedMessageField;
    
    private processesProcessProcessWorkflowClass processWorkflowClassField;
    
    private processesProcessProcessError processErrorField;
    
    private processesProcessCurrentWorkItems currentWorkItemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string processId {
        get {
            return this.processIdField;
        }
        set {
            this.processIdField = value;
        }
    }
    
    /// <remarks/>
    public string processRadNumber {
        get {
            return this.processRadNumberField;
        }
        set {
            this.processRadNumberField = value;
        }
    }
    
    /// <remarks/>
    public processesProcessSavedMessage savedMessage {
        get {
            return this.savedMessageField;
        }
        set {
            this.savedMessageField = value;
        }
    }
    
    /// <remarks/>
    public processesProcessProcessWorkflowClass processWorkflowClass {
        get {
            return this.processWorkflowClassField;
        }
        set {
            this.processWorkflowClassField = value;
        }
    }
    
    /// <remarks/>
    public processesProcessProcessError processError {
        get {

            if (processErrorField == null)
                processErrorField = new processesProcessProcessError();

            return this.processErrorField;
        }
        set {
            this.processErrorField = value;
        }
    }
    
    /// <remarks/>
    public processesProcessCurrentWorkItems CurrentWorkItems {
        get {
            return this.currentWorkItemsField;
        }
        set {
            this.currentWorkItemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class processesProcessSavedMessage {
    
    private string entitiesField;
    
    /// <remarks/>
    public string Entities {
        get {
            return this.entitiesField;
        }
        set {
            this.entitiesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class processesProcessProcessWorkflowClass {
    
    private string workflowClassIdField;
    
    private string workflowClassNameField;
    
    private string workflowClassDisplayNameField;
    
    private string workflowClassDescriptionField;
    
    private string workflowClassHelpTextField;
    
    private string workflowClassDisplayOrderField;
    
    private string workflowClassCreationDateField;
    
    private string workflowClassGlobalFormField;
    
    private string workflowClassAllocationPrincipleField;
    
    private string workflowClassProcessTypeField;
    
    private string workflowClassDisplayField;
    
    private string workflowClassUseParentRadicationNumberField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string workflowClassId {
        get {
            return this.workflowClassIdField;
        }
        set {
            this.workflowClassIdField = value;
        }
    }
    
    /// <remarks/>
    public string workflowClassName {
        get {
            return this.workflowClassNameField;
        }
        set {
            this.workflowClassNameField = value;
        }
    }
    
    /// <remarks/>
    public string workflowClassDisplayName {
        get {
            return this.workflowClassDisplayNameField;
        }
        set {
            this.workflowClassDisplayNameField = value;
        }
    }
    
    /// <remarks/>
    public string workflowClassDescription {
        get {
            return this.workflowClassDescriptionField;
        }
        set {
            this.workflowClassDescriptionField = value;
        }
    }
    
    /// <remarks/>
    public string workflowClassHelpText {
        get {
            return this.workflowClassHelpTextField;
        }
        set {
            this.workflowClassHelpTextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string workflowClassDisplayOrder {
        get {
            return this.workflowClassDisplayOrderField;
        }
        set {
            this.workflowClassDisplayOrderField = value;
        }
    }
    
    /// <remarks/>
    public string workflowClassCreationDate {
        get {
            return this.workflowClassCreationDateField;
        }
        set {
            this.workflowClassCreationDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string workflowClassGlobalForm {
        get {
            return this.workflowClassGlobalFormField;
        }
        set {
            this.workflowClassGlobalFormField = value;
        }
    }
    
    /// <remarks/>
    public string workflowClassAllocationPrinciple {
        get {
            return this.workflowClassAllocationPrincipleField;
        }
        set {
            this.workflowClassAllocationPrincipleField = value;
        }
    }
    
    /// <remarks/>
    public string workflowClassProcessType {
        get {
            return this.workflowClassProcessTypeField;
        }
        set {
            this.workflowClassProcessTypeField = value;
        }
    }
    
    /// <remarks/>
    public string workflowClassDisplay {
        get {
            return this.workflowClassDisplayField;
        }
        set {
            this.workflowClassDisplayField = value;
        }
    }
    
    /// <remarks/>
    public string workflowClassUseParentRadicationNumber {
        get {
            return this.workflowClassUseParentRadicationNumberField;
        }
        set {
            this.workflowClassUseParentRadicationNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class processesProcessProcessError {
    
    private string errorCodeField;
    
    private processesProcessProcessErrorErrorMessage errorMessageField;
    
    /// <remarks/>
    public string errorCode {
        get {
            return this.errorCodeField;
        }
        set {
            this.errorCodeField = value;
        }
    }
    
    /// <remarks/>
    public processesProcessProcessErrorErrorMessage errorMessage {
        get {
            return this.errorMessageField;
        }
        set {
            this.errorMessageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class processesProcessProcessErrorErrorMessage {
    
    private processesProcessProcessErrorErrorMessageEntities entitiesField;
    
    private string[] textField;
    
    /// <remarks/>
    public processesProcessProcessErrorErrorMessageEntities Entities {
        get {
            return this.entitiesField;
        }
        set {
            this.entitiesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class processesProcessProcessErrorErrorMessageEntities {
    
    private string pathField;
    
    private string atribField;
    
    private string valueField;
    
    private string errorMessageField;
    
    /// <remarks/>
    public string Path {
        get {
            return this.pathField;
        }
        set {
            this.pathField = value;
        }
    }
    
    /// <remarks/>
    public string Atrib {
        get {
            return this.atribField;
        }
        set {
            this.atribField = value;
        }
    }
    
    /// <remarks/>
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    public string ErrorMessage {
        get {
            return this.errorMessageField;
        }
        set {
            this.errorMessageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class processesProcessCurrentWorkItems {
    
    private processesProcessCurrentWorkItemsWorkItem workItemField;
    
    private string[] textField;
    
    /// <remarks/>
    public processesProcessCurrentWorkItemsWorkItem workItem {
        get {
            return this.workItemField;
        }
        set {
            this.workItemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class processesProcessCurrentWorkItemsWorkItem {
    
    private string workItemIdField;
    
    private string workItemStateField;
    
    private string workItemEntryDateField;
    
    private string workItemDurationField;
    
    private string workItemEstimatedSolutionDateField;
    
    private processesProcessCurrentWorkItemsWorkItemTask taskField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string workItemId {
        get {
            return this.workItemIdField;
        }
        set {
            this.workItemIdField = value;
        }
    }
    
    /// <remarks/>
    public string workItemState {
        get {
            return this.workItemStateField;
        }
        set {
            this.workItemStateField = value;
        }
    }
    
    /// <remarks/>
    public string workItemEntryDate {
        get {
            return this.workItemEntryDateField;
        }
        set {
            this.workItemEntryDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string workItemDuration {
        get {
            return this.workItemDurationField;
        }
        set {
            this.workItemDurationField = value;
        }
    }
    
    /// <remarks/>
    public string workItemEstimatedSolutionDate {
        get {
            return this.workItemEstimatedSolutionDateField;
        }
        set {
            this.workItemEstimatedSolutionDateField = value;
        }
    }
    
    /// <remarks/>
    public processesProcessCurrentWorkItemsWorkItemTask task {
        get {
            return this.taskField;
        }
        set {
            this.taskField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class processesProcessCurrentWorkItemsWorkItemTask {
    
    private string taskIdField;
    
    private string taskNameField;
    
    private string taskDisplayNameField;
    
    private string taskDescriptionField;
    
    private string taskHelpTextField;
    
    private string taskEstimatedDurationField;
    
    private string taskTypeField;
    
    private string taskCostField;
    
    private string taskPriorityField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string taskId {
        get {
            return this.taskIdField;
        }
        set {
            this.taskIdField = value;
        }
    }
    
    /// <remarks/>
    public string taskName {
        get {
            return this.taskNameField;
        }
        set {
            this.taskNameField = value;
        }
    }
    
    /// <remarks/>
    public string taskDisplayName {
        get {
            return this.taskDisplayNameField;
        }
        set {
            this.taskDisplayNameField = value;
        }
    }
    
    /// <remarks/>
    public string taskDescription {
        get {
            return this.taskDescriptionField;
        }
        set {
            this.taskDescriptionField = value;
        }
    }
    
    /// <remarks/>
    public string taskHelpText {
        get {
            return this.taskHelpTextField;
        }
        set {
            this.taskHelpTextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string taskEstimatedDuration {
        get {
            return this.taskEstimatedDurationField;
        }
        set {
            this.taskEstimatedDurationField = value;
        }
    }
    
    /// <remarks/>
    public string taskType {
        get {
            return this.taskTypeField;
        }
        set {
            this.taskTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string taskCost {
        get {
            return this.taskCostField;
        }
        set {
            this.taskCostField = value;
        }
    }
    
    /// <remarks/>
    public string taskPriority {
        get {
            return this.taskPriorityField;
        }
        set {
            this.taskPriorityField = value;
        }
    }
}
