//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 

namespace Bizagi.Proxy.Layer.HUB.BizagiSOAObjects.CreateCase
{ 

/// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
[XmlRoot("BizAgiWSParam")]
public partial class BizAgiWSParam<T> where T: class {
    
    private string domainField;
    
    private string userNameField;
    
    private BizAgiWSParamCase<T>[] casesField;

        public BizAgiWSParam(string domain, string userName)
        {
            this.domain = domain;
            this.userName = userName;
        }


        public BizAgiWSParam()
        {

        }



        /// <remarks/>
        public string domain {
        get {
            return this.domainField;
        }
        set {
            this.domainField = value;
        }
    }
    
    /// <remarks/>
    public string userName {
        get {
            return this.userNameField;
        }
        set {
            this.userNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Case", IsNullable=false)]
    public BizAgiWSParamCase<T>[] Cases
        {
           
            get {
                if (casesField == null)
                {
                    casesField = new BizAgiWSParamCase<T>[1];
                }
                return this.casesField;
        }
        set {
            this.casesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class BizAgiWSParamCase<T> where T : class {
    
    private string processField;
    
    private string organizationField;
    
    private BizAgiWSParamCaseEntities<T> entitiesField;

    public BizAgiWSParamCase(string nombreProceso)
    {
        processField = nombreProceso;
    }

    public BizAgiWSParamCase()
    {
    }



        /// <remarks/>
        public string Process {
        get {
            return this.processField;
        }
        set {
            this.processField = value;
        }
    }
    
    /// <remarks/>
    public string Organization {
        get {
            return this.organizationField;
        }
        set {
            this.organizationField = value;
        }
    }
    
    /// <remarks/>
    public BizAgiWSParamCaseEntities<T> Entities {
        get {

                if (entitiesField == null)
                {
                    entitiesField = new BizAgiWSParamCaseEntities<T>();
                }
                return this.entitiesField;
        }
        set {
            this.entitiesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class BizAgiWSParamCaseEntities<T> where T: class {


    private T _infoCaso;
   [XmlElement("M_CAT_GestionDesembolso")]
    public T InfoCaso
    {
        get
        {
            if(_infoCaso == null)
                _infoCaso = Activator.CreateInstance<T>();
            return _infoCaso;
        }
        set { _infoCaso = value; }
    }



}
}