//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 

namespace Bizagi.Proxy.Layer.HUB.BizagiSOAObjects.PeformActivityGeneric
{
    /// <remarks/>
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    //[System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    //[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    [XmlRoot("BizAgiWSParam")]
    public partial class BizAgiWSParam
    {

        private string domainField;

        private string userNameField;

        private BizAgiWSParamActivityData activityDataField;


        /// <remarks/>
        public string domain
        {
            get
            {
                return this.domainField;
            }
            set
            {
                this.domainField = value;
            }
        }

        /// <remarks/>
        public string userName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }

        /// <remarks/>
        public BizAgiWSParamActivityData ActivityData
        {
            get
            {
                if (activityDataField == null)
                    activityDataField = new BizAgiWSParamActivityData();
                return this.activityDataField;
            }
            set
            {
                this.activityDataField = value;
            }
        }

       
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class BizAgiWSParamActivityData
    {

        private string idCaseField;

        private string taskNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string idCase
        {
            get
            {
                return this.idCaseField;
            }
            set
            {
                this.idCaseField = value;
            }
        }

        /// <remarks/>
        public string taskName
        {
            get
            {
                return this.taskNameField;
            }
            set
            {
                this.taskNameField = value;
            }
        }
    }


}