//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizagi.Proxy.Layer.BancoProyectos.CrearEstructuraInmob.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:7800/esb/services/soap")]
        public string Bizagi_Proxy_Layer_BancoProyectos_CrearEstructuraInmob_CrearEstructuraInmob_BancoProyectos_CrearEstructuraInmobiliaria_Service {
            get {
                return ((string)(this["Bizagi_Proxy_Layer_BancoProyectos_CrearEstructuraInmob_CrearEstructuraInmob_Banco" +
                    "Proyectos_CrearEstructuraInmobiliaria_Service"]));
            }
        }
    }
}
