//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizagi.ECM.Manager.ECMService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestDtoOfGestorDtopCDoQcXC", Namespace="http://schemas.datacontract.org/2004/07/WorkManager.Model.Entities")]
    [System.SerializableAttribute()]
    public partial class RequestDtoOfGestorDtopCDoQcXC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Bizagi.ECM.Manager.ECMService.FileDto> ArchivosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Bizagi.ECM.Manager.ECMService.GestorDto DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Bizagi.ECM.Manager.ECMService.HeaderDto HeaderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Bizagi.ECM.Manager.ECMService.FileDto> Archivos {
            get {
                return this.ArchivosField;
            }
            set {
                if ((object.ReferenceEquals(this.ArchivosField, value) != true)) {
                    this.ArchivosField = value;
                    this.RaisePropertyChanged("Archivos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Bizagi.ECM.Manager.ECMService.GestorDto Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Bizagi.ECM.Manager.ECMService.HeaderDto Header {
            get {
                return this.HeaderField;
            }
            set {
                if ((object.ReferenceEquals(this.HeaderField, value) != true)) {
                    this.HeaderField = value;
                    this.RaisePropertyChanged("Header");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GestorDto", Namespace="http://schemas.datacontract.org/2004/07/WorkManager.Model.Entities")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Bizagi.ECM.Manager.ECMService.GestorDocumentalDto))]
    public partial class GestorDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AplicacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresyApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoIdentificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransaccionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Aplicacion {
            get {
                return this.AplicacionField;
            }
            set {
                if ((object.ReferenceEquals(this.AplicacionField, value) != true)) {
                    this.AplicacionField = value;
                    this.RaisePropertyChanged("Aplicacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identificacion {
            get {
                return this.IdentificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificacionField, value) != true)) {
                    this.IdentificacionField = value;
                    this.RaisePropertyChanged("Identificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombresyApellidos {
            get {
                return this.NombresyApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresyApellidosField, value) != true)) {
                    this.NombresyApellidosField = value;
                    this.RaisePropertyChanged("NombresyApellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoIdentificacion {
            get {
                return this.TipoIdentificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoIdentificacionField, value) != true)) {
                    this.TipoIdentificacionField = value;
                    this.RaisePropertyChanged("TipoIdentificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Transaccion {
            get {
                return this.TransaccionField;
            }
            set {
                if ((object.ReferenceEquals(this.TransaccionField, value) != true)) {
                    this.TransaccionField = value;
                    this.RaisePropertyChanged("Transaccion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HeaderDto", Namespace="http://schemas.datacontract.org/2004/07/WorkManager.Model.Entities")]
    [System.SerializableAttribute()]
    public partial class HeaderDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileDto", Namespace="http://schemas.datacontract.org/2004/07/WorkManager.Model.Entities")]
    [System.SerializableAttribute()]
    public partial class FileDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Base64StringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoTipoDocumentalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Base64String {
            get {
                return this.Base64StringField;
            }
            set {
                if ((object.ReferenceEquals(this.Base64StringField, value) != true)) {
                    this.Base64StringField = value;
                    this.RaisePropertyChanged("Base64String");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoTipoDocumental {
            get {
                return this.CodigoTipoDocumentalField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoTipoDocumentalField, value) != true)) {
                    this.CodigoTipoDocumentalField = value;
                    this.RaisePropertyChanged("CodigoTipoDocumental");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ext {
            get {
                return this.ExtField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtField, value) != true)) {
                    this.ExtField = value;
                    this.RaisePropertyChanged("Ext");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GestorDocumentalDto", Namespace="http://schemas.datacontract.org/2004/07/WorkManager.Model.Entities")]
    [System.SerializableAttribute()]
    public partial class GestorDocumentalDto : Bizagi.ECM.Manager.ECMService.GestorDto {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Bizagi.ECM.Manager.ECMService.DocumentoDto> DocumentosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RadicadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Bizagi.ECM.Manager.ECMService.DocumentoDto> Documentos {
            get {
                return this.DocumentosField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentosField, value) != true)) {
                    this.DocumentosField = value;
                    this.RaisePropertyChanged("Documentos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Radicado {
            get {
                return this.RadicadoField;
            }
            set {
                if ((object.ReferenceEquals(this.RadicadoField, value) != true)) {
                    this.RadicadoField = value;
                    this.RaisePropertyChanged("Radicado");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentoDto", Namespace="http://schemas.datacontract.org/2004/07/WorkManager.Model.Entities")]
    [System.SerializableAttribute()]
    public partial class DocumentoDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoArchivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoDirectorioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDocumentoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoArchivo {
            get {
                return this.CodigoArchivoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoArchivoField, value) != true)) {
                    this.CodigoArchivoField = value;
                    this.RaisePropertyChanged("CodigoArchivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoDirectorio {
            get {
                return this.CodigoDirectorioField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoDirectorioField, value) != true)) {
                    this.CodigoDirectorioField = value;
                    this.RaisePropertyChanged("CodigoDirectorio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ext {
            get {
                return this.ExtField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtField, value) != true)) {
                    this.ExtField = value;
                    this.RaisePropertyChanged("Ext");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreDocumento {
            get {
                return this.NombreDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreDocumentoField, value) != true)) {
                    this.NombreDocumentoField = value;
                    this.RaisePropertyChanged("NombreDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDocumento {
            get {
                return this.TipoDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDocumentoField, value) != true)) {
                    this.TipoDocumentoField = value;
                    this.RaisePropertyChanged("TipoDocumento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseDtoOfstring", Namespace="http://schemas.datacontract.org/2004/07/WorkManager.Model.Entities")]
    [System.SerializableAttribute()]
    public partial class ResponseDtoOfstring : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> CodeFilesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SucessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> CodeFiles {
            get {
                return this.CodeFilesField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeFilesField, value) != true)) {
                    this.CodeFilesField = value;
                    this.RaisePropertyChanged("CodeFiles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Results {
            get {
                return this.ResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultsField, value) != true)) {
                    this.ResultsField = value;
                    this.RaisePropertyChanged("Results");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Sucess {
            get {
                return this.SucessField;
            }
            set {
                if ((this.SucessField.Equals(value) != true)) {
                    this.SucessField = value;
                    this.RaisePropertyChanged("Sucess");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseDtoOfArrayOfGestorDocumentalDtopCDoQcXC", Namespace="http://schemas.datacontract.org/2004/07/WorkManager.Model.Entities")]
    [System.SerializableAttribute()]
    public partial class ResponseDtoOfArrayOfGestorDocumentalDtopCDoQcXC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> CodeFilesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Bizagi.ECM.Manager.ECMService.GestorDocumentalDto> ResultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SucessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> CodeFiles {
            get {
                return this.CodeFilesField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeFilesField, value) != true)) {
                    this.CodeFilesField = value;
                    this.RaisePropertyChanged("CodeFiles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Bizagi.ECM.Manager.ECMService.GestorDocumentalDto> Results {
            get {
                return this.ResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultsField, value) != true)) {
                    this.ResultsField = value;
                    this.RaisePropertyChanged("Results");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Sucess {
            get {
                return this.SucessField;
            }
            set {
                if ((this.SucessField.Equals(value) != true)) {
                    this.SucessField = value;
                    this.RaisePropertyChanged("Sucess");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ECMService.IApi")]
    public interface IApi {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApi/Gestor_Insertar", ReplyAction="http://tempuri.org/IApi/Gestor_InsertarResponse")]
        Bizagi.ECM.Manager.ECMService.Gestor_InsertarResponse Gestor_Insertar(Bizagi.ECM.Manager.ECMService.Gestor_InsertarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApi/Gestor_Insertar", ReplyAction="http://tempuri.org/IApi/Gestor_InsertarResponse")]
        System.Threading.Tasks.Task<Bizagi.ECM.Manager.ECMService.Gestor_InsertarResponse> Gestor_InsertarAsync(Bizagi.ECM.Manager.ECMService.Gestor_InsertarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApi/Gestor_CambiarDocumento", ReplyAction="http://tempuri.org/IApi/Gestor_CambiarDocumentoResponse")]
        Bizagi.ECM.Manager.ECMService.Gestor_CambiarDocumentoResponse Gestor_CambiarDocumento(Bizagi.ECM.Manager.ECMService.Gestor_CambiarDocumentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApi/Gestor_CambiarDocumento", ReplyAction="http://tempuri.org/IApi/Gestor_CambiarDocumentoResponse")]
        System.Threading.Tasks.Task<Bizagi.ECM.Manager.ECMService.Gestor_CambiarDocumentoResponse> Gestor_CambiarDocumentoAsync(Bizagi.ECM.Manager.ECMService.Gestor_CambiarDocumentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApi/Gestor_EliminarDocumento", ReplyAction="http://tempuri.org/IApi/Gestor_EliminarDocumentoResponse")]
        Bizagi.ECM.Manager.ECMService.Gestor_EliminarDocumentoResponse Gestor_EliminarDocumento(Bizagi.ECM.Manager.ECMService.Gestor_EliminarDocumentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApi/Gestor_EliminarDocumento", ReplyAction="http://tempuri.org/IApi/Gestor_EliminarDocumentoResponse")]
        System.Threading.Tasks.Task<Bizagi.ECM.Manager.ECMService.Gestor_EliminarDocumentoResponse> Gestor_EliminarDocumentoAsync(Bizagi.ECM.Manager.ECMService.Gestor_EliminarDocumentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApi/Gestor_ConsultarDocumento", ReplyAction="http://tempuri.org/IApi/Gestor_ConsultarDocumentoResponse")]
        Bizagi.ECM.Manager.ECMService.Gestor_ConsultarDocumentoResponse Gestor_ConsultarDocumento(Bizagi.ECM.Manager.ECMService.Gestor_ConsultarDocumentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApi/Gestor_ConsultarDocumento", ReplyAction="http://tempuri.org/IApi/Gestor_ConsultarDocumentoResponse")]
        System.Threading.Tasks.Task<Bizagi.ECM.Manager.ECMService.Gestor_ConsultarDocumentoResponse> Gestor_ConsultarDocumentoAsync(Bizagi.ECM.Manager.ECMService.Gestor_ConsultarDocumentoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Gestor_Insertar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Gestor_InsertarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Bizagi.ECM.Manager.ECMService.RequestDtoOfGestorDtopCDoQcXC request;
        
        public Gestor_InsertarRequest() {
        }
        
        public Gestor_InsertarRequest(Bizagi.ECM.Manager.ECMService.RequestDtoOfGestorDtopCDoQcXC request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Gestor_InsertarResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Gestor_InsertarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Bizagi.ECM.Manager.ECMService.ResponseDtoOfstring Gestor_InsertarResult;
        
        public Gestor_InsertarResponse() {
        }
        
        public Gestor_InsertarResponse(Bizagi.ECM.Manager.ECMService.ResponseDtoOfstring Gestor_InsertarResult) {
            this.Gestor_InsertarResult = Gestor_InsertarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Gestor_CambiarDocumento", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Gestor_CambiarDocumentoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Bizagi.ECM.Manager.ECMService.HeaderDto header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string codigo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public Bizagi.ECM.Manager.ECMService.FileDto documento;
        
        public Gestor_CambiarDocumentoRequest() {
        }
        
        public Gestor_CambiarDocumentoRequest(Bizagi.ECM.Manager.ECMService.HeaderDto header, string codigo, Bizagi.ECM.Manager.ECMService.FileDto documento) {
            this.header = header;
            this.codigo = codigo;
            this.documento = documento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Gestor_CambiarDocumentoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Gestor_CambiarDocumentoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Bizagi.ECM.Manager.ECMService.ResponseDtoOfstring Gestor_CambiarDocumentoResult;
        
        public Gestor_CambiarDocumentoResponse() {
        }
        
        public Gestor_CambiarDocumentoResponse(Bizagi.ECM.Manager.ECMService.ResponseDtoOfstring Gestor_CambiarDocumentoResult) {
            this.Gestor_CambiarDocumentoResult = Gestor_CambiarDocumentoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Gestor_EliminarDocumento", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Gestor_EliminarDocumentoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Bizagi.ECM.Manager.ECMService.HeaderDto header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string codigoAchivo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string radicado;
        
        public Gestor_EliminarDocumentoRequest() {
        }
        
        public Gestor_EliminarDocumentoRequest(Bizagi.ECM.Manager.ECMService.HeaderDto header, string codigoAchivo, string radicado) {
            this.header = header;
            this.codigoAchivo = codigoAchivo;
            this.radicado = radicado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Gestor_EliminarDocumentoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Gestor_EliminarDocumentoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Bizagi.ECM.Manager.ECMService.ResponseDtoOfstring Gestor_EliminarDocumentoResult;
        
        public Gestor_EliminarDocumentoResponse() {
        }
        
        public Gestor_EliminarDocumentoResponse(Bizagi.ECM.Manager.ECMService.ResponseDtoOfstring Gestor_EliminarDocumentoResult) {
            this.Gestor_EliminarDocumentoResult = Gestor_EliminarDocumentoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Gestor_ConsultarDocumento", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Gestor_ConsultarDocumentoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Bizagi.ECM.Manager.ECMService.HeaderDto header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string radicado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string identificacion;
        
        public Gestor_ConsultarDocumentoRequest() {
        }
        
        public Gestor_ConsultarDocumentoRequest(Bizagi.ECM.Manager.ECMService.HeaderDto header, string radicado, string identificacion) {
            this.header = header;
            this.radicado = radicado;
            this.identificacion = identificacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Gestor_ConsultarDocumentoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Gestor_ConsultarDocumentoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Bizagi.ECM.Manager.ECMService.ResponseDtoOfArrayOfGestorDocumentalDtopCDoQcXC Gestor_ConsultarDocumentoResult;
        
        public Gestor_ConsultarDocumentoResponse() {
        }
        
        public Gestor_ConsultarDocumentoResponse(Bizagi.ECM.Manager.ECMService.ResponseDtoOfArrayOfGestorDocumentalDtopCDoQcXC Gestor_ConsultarDocumentoResult) {
            this.Gestor_ConsultarDocumentoResult = Gestor_ConsultarDocumentoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IApiChannel : Bizagi.ECM.Manager.ECMService.IApi, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ApiClient : System.ServiceModel.ClientBase<Bizagi.ECM.Manager.ECMService.IApi>, Bizagi.ECM.Manager.ECMService.IApi {
        
        public ApiClient() {
        }
        
        public ApiClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ApiClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Bizagi.ECM.Manager.ECMService.Gestor_InsertarResponse Gestor_Insertar(Bizagi.ECM.Manager.ECMService.Gestor_InsertarRequest request) {
            return base.Channel.Gestor_Insertar(request);
        }
        
        public System.Threading.Tasks.Task<Bizagi.ECM.Manager.ECMService.Gestor_InsertarResponse> Gestor_InsertarAsync(Bizagi.ECM.Manager.ECMService.Gestor_InsertarRequest request) {
            return base.Channel.Gestor_InsertarAsync(request);
        }
        
        public Bizagi.ECM.Manager.ECMService.Gestor_CambiarDocumentoResponse Gestor_CambiarDocumento(Bizagi.ECM.Manager.ECMService.Gestor_CambiarDocumentoRequest request) {
            return base.Channel.Gestor_CambiarDocumento(request);
        }
        
        public System.Threading.Tasks.Task<Bizagi.ECM.Manager.ECMService.Gestor_CambiarDocumentoResponse> Gestor_CambiarDocumentoAsync(Bizagi.ECM.Manager.ECMService.Gestor_CambiarDocumentoRequest request) {
            return base.Channel.Gestor_CambiarDocumentoAsync(request);
        }
        
        public Bizagi.ECM.Manager.ECMService.Gestor_EliminarDocumentoResponse Gestor_EliminarDocumento(Bizagi.ECM.Manager.ECMService.Gestor_EliminarDocumentoRequest request) {
            return base.Channel.Gestor_EliminarDocumento(request);
        }
        
        public System.Threading.Tasks.Task<Bizagi.ECM.Manager.ECMService.Gestor_EliminarDocumentoResponse> Gestor_EliminarDocumentoAsync(Bizagi.ECM.Manager.ECMService.Gestor_EliminarDocumentoRequest request) {
            return base.Channel.Gestor_EliminarDocumentoAsync(request);
        }
        
        public Bizagi.ECM.Manager.ECMService.Gestor_ConsultarDocumentoResponse Gestor_ConsultarDocumento(Bizagi.ECM.Manager.ECMService.Gestor_ConsultarDocumentoRequest request) {
            return base.Channel.Gestor_ConsultarDocumento(request);
        }
        
        public System.Threading.Tasks.Task<Bizagi.ECM.Manager.ECMService.Gestor_ConsultarDocumentoResponse> Gestor_ConsultarDocumentoAsync(Bizagi.ECM.Manager.ECMService.Gestor_ConsultarDocumentoRequest request) {
            return base.Channel.Gestor_ConsultarDocumentoAsync(request);
        }
    }
}
