//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizagi.Proxy.Layer.Cobis.RecuperarInfoPN.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:7800/esb/services/soap/clientepersonanatural/recuperarinformacio" +
            "n/v1")]
        public string Bizagi_Proxy_Layer_Cobis_RecuperarInfoPN_Cliente_RecuperarInfoPN_ClientePersonaNatural_RecuperarInformacion_Service {
            get {
                return ((string)(this["Bizagi_Proxy_Layer_Cobis_RecuperarInfoPN_Cliente_RecuperarInfoPN_ClientePersonaNa" +
                    "tural_RecuperarInformacion_Service"]));
            }
        }
    }
}
