//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8745
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 



public class InfoSolicitudSeguros {
    
    private string oidReclamacionSeguroField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string OidReclamacionSeguro {
        get {
            return this.oidReclamacionSeguroField;
        }
        set {
            this.oidReclamacionSeguroField = value;
        }
    }
}
