//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Bizagi.Proxy.Layer.BancoProyectos.CrearEstructuraInmob.CrearEstructuraInmob {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BancoProyectos_CrearEstructuraInmobiliaria_Binding12", Namespace="http://www.fna.gov.co/esb/services/bancoproyectos/crearestructurainmobiliaria/v1")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InformacionEstructuraInmobiliaria))]
    public partial class BancoProyectos_CrearEstructuraInmobiliaria_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private ConsumerHeader consumerHeaderField;
        
        private System.Threading.SendOrPostCallback CrearEstructuraInmobiliariaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BancoProyectos_CrearEstructuraInmobiliaria_Service() {
            this.SoapVersion = System.Web.Services.Protocols.SoapProtocolVersion.Soap12;
            this.Url = global::Bizagi.Proxy.Layer.BancoProyectos.CrearEstructuraInmob.Properties.Settings.Default.Bizagi_Proxy_Layer_BancoProyectos_CrearEstructuraInmob_CrearEstructuraInmob_BancoProyectos_CrearEstructuraInmobiliaria_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public ConsumerHeader consumerHeader {
            get {
                return this.consumerHeaderField;
            }
            set {
                this.consumerHeaderField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CrearEstructuraInmobiliariaCompletedEventHandler CrearEstructuraInmobiliariaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("consumerHeader")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("CrearEstructuraInmobiliaria", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("CrearEstructuraInmobiliariaResponse", Namespace="http://www.fna.gov.co/esb/services/bancoproyectos/crearestructurainmobiliaria/v1")]
        public ServicioResponse CrearEstructuraInmobiliaria([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.fna.gov.co/esb/services/bancoproyectos/crearestructurainmobiliaria/v1")] ServiceRequest CrearEstructuraInmobiliariaRequest) {
            object[] results = this.Invoke("CrearEstructuraInmobiliaria", new object[] {
                        CrearEstructuraInmobiliariaRequest});
            return ((ServicioResponse)(results[0]));
        }
        
        /// <remarks/>
        public void CrearEstructuraInmobiliariaAsync(ServiceRequest CrearEstructuraInmobiliariaRequest) {
            this.CrearEstructuraInmobiliariaAsync(CrearEstructuraInmobiliariaRequest, null);
        }
        
        /// <remarks/>
        public void CrearEstructuraInmobiliariaAsync(ServiceRequest CrearEstructuraInmobiliariaRequest, object userState) {
            if ((this.CrearEstructuraInmobiliariaOperationCompleted == null)) {
                this.CrearEstructuraInmobiliariaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCrearEstructuraInmobiliariaOperationCompleted);
            }
            this.InvokeAsync("CrearEstructuraInmobiliaria", new object[] {
                        CrearEstructuraInmobiliariaRequest}, this.CrearEstructuraInmobiliariaOperationCompleted, userState);
        }
        
        private void OnCrearEstructuraInmobiliariaOperationCompleted(object arg) {
            if ((this.CrearEstructuraInmobiliariaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CrearEstructuraInmobiliariaCompleted(this, new CrearEstructuraInmobiliariaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fna.gov.co/esb/services/cl/consumerheader")]
    [System.Xml.Serialization.XmlRootAttribute("consumerHeader", Namespace="http://www.fna.gov.co/esb/services/bancoproyectos/crearestructurainmobiliaria/v1", IsNullable=false)]
    public partial class ConsumerHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string systemIdField;
        
        private string clientTransactionIDField;
        
        private string endHostField;
        
        private string endUserField;
        
        private System.DateTime datetimeField;
        
        private bool datetimeFieldSpecified;
        
        private RequestData requestDataField;
        
        private Property[] messageContextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string systemId {
            get {
                return this.systemIdField;
            }
            set {
                this.systemIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string clientTransactionID {
            get {
                return this.clientTransactionIDField;
            }
            set {
                this.clientTransactionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string endHost {
            get {
                return this.endHostField;
            }
            set {
                this.endHostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string endUser {
            get {
                return this.endUserField;
            }
            set {
                this.endUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime datetime {
            get {
                return this.datetimeField;
            }
            set {
                this.datetimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool datetimeSpecified {
            get {
                return this.datetimeFieldSpecified;
            }
            set {
                this.datetimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RequestData requestData {
            get {
                return this.requestDataField;
            }
            set {
                this.requestDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("property", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Property[] messageContext {
            get {
                return this.messageContextField;
            }
            set {
                this.messageContextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fna.gov.co/esb/services/cl/consumerheader")]
    public partial class RequestData {
        
        private UserId userIdField;
        
        private Destination destinationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UserId userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Destination destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fna.gov.co/esb/services/cl/consumerheader")]
    public partial class UserId {
        
        private string userNameField;
        
        private string userTokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userToken {
            get {
                return this.userTokenField;
            }
            set {
                this.userTokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fna.gov.co/esb/services/bancoproyectos/crearestructurainmobiliaria/v1")]
    public partial class ServicioResponse {
        
        private int idEstructuraField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idEstructura {
            get {
                return this.idEstructuraField;
            }
            set {
                this.idEstructuraField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DetalleAreaLote_Crear))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fna.gov.co/cim/businessentities/detallearealote")]
    public partial class DetalleAreaLote {
        
        private decimal areaBrutaField;
        
        private bool areaBrutaFieldSpecified;
        
        private decimal areaProteccionField;
        
        private bool areaProteccionFieldSpecified;
        
        private decimal areaAfectadaField;
        
        private bool areaAfectadaFieldSpecified;
        
        private decimal areaCesionField;
        
        private bool areaCesionFieldSpecified;
        
        private decimal areaUtilField;
        
        private bool areaUtilFieldSpecified;
        
        private decimal areaTotalConstruidaField;
        
        private bool areaTotalConstruidaFieldSpecified;
        
        private decimal areaConstruidaPrimerPisoField;
        
        private bool areaConstruidaPrimerPisoFieldSpecified;
        
        private decimal areaVendibleViviendaField;
        
        private bool areaVendibleViviendaFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal areaBruta {
            get {
                return this.areaBrutaField;
            }
            set {
                this.areaBrutaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool areaBrutaSpecified {
            get {
                return this.areaBrutaFieldSpecified;
            }
            set {
                this.areaBrutaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal areaProteccion {
            get {
                return this.areaProteccionField;
            }
            set {
                this.areaProteccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool areaProteccionSpecified {
            get {
                return this.areaProteccionFieldSpecified;
            }
            set {
                this.areaProteccionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal areaAfectada {
            get {
                return this.areaAfectadaField;
            }
            set {
                this.areaAfectadaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool areaAfectadaSpecified {
            get {
                return this.areaAfectadaFieldSpecified;
            }
            set {
                this.areaAfectadaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal areaCesion {
            get {
                return this.areaCesionField;
            }
            set {
                this.areaCesionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool areaCesionSpecified {
            get {
                return this.areaCesionFieldSpecified;
            }
            set {
                this.areaCesionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal areaUtil {
            get {
                return this.areaUtilField;
            }
            set {
                this.areaUtilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool areaUtilSpecified {
            get {
                return this.areaUtilFieldSpecified;
            }
            set {
                this.areaUtilFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal areaTotalConstruida {
            get {
                return this.areaTotalConstruidaField;
            }
            set {
                this.areaTotalConstruidaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool areaTotalConstruidaSpecified {
            get {
                return this.areaTotalConstruidaFieldSpecified;
            }
            set {
                this.areaTotalConstruidaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal areaConstruidaPrimerPiso {
            get {
                return this.areaConstruidaPrimerPisoField;
            }
            set {
                this.areaConstruidaPrimerPisoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool areaConstruidaPrimerPisoSpecified {
            get {
                return this.areaConstruidaPrimerPisoFieldSpecified;
            }
            set {
                this.areaConstruidaPrimerPisoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal areaVendibleVivienda {
            get {
                return this.areaVendibleViviendaField;
            }
            set {
                this.areaVendibleViviendaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool areaVendibleViviendaSpecified {
            get {
                return this.areaVendibleViviendaFieldSpecified;
            }
            set {
                this.areaVendibleViviendaFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fna.gov.co/esb/services/bancoproyectos/crearestructurainmobiliaria/v1")]
    public partial class DetalleAreaLote_Crear : DetalleAreaLote {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ClasificacionParqueo_Crear))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fna.gov.co/cim/businessentities/clasificacionparqueo")]
    public partial class ClasificacionParqueo {
        
        private int cantidadPrivadosField;
        
        private bool cantidadPrivadosFieldSpecified;
        
        private int cantidadVisitantesField;
        
        private bool cantidadVisitantesFieldSpecified;
        
        private int cantidadComunalesField;
        
        private bool cantidadComunalesFieldSpecified;
        
        private int cantidadDiscapacitadosField;
        
        private bool cantidadDiscapacitadosFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cantidadPrivados {
            get {
                return this.cantidadPrivadosField;
            }
            set {
                this.cantidadPrivadosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cantidadPrivadosSpecified {
            get {
                return this.cantidadPrivadosFieldSpecified;
            }
            set {
                this.cantidadPrivadosFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cantidadVisitantes {
            get {
                return this.cantidadVisitantesField;
            }
            set {
                this.cantidadVisitantesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cantidadVisitantesSpecified {
            get {
                return this.cantidadVisitantesFieldSpecified;
            }
            set {
                this.cantidadVisitantesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cantidadComunales {
            get {
                return this.cantidadComunalesField;
            }
            set {
                this.cantidadComunalesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cantidadComunalesSpecified {
            get {
                return this.cantidadComunalesFieldSpecified;
            }
            set {
                this.cantidadComunalesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cantidadDiscapacitados {
            get {
                return this.cantidadDiscapacitadosField;
            }
            set {
                this.cantidadDiscapacitadosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cantidadDiscapacitadosSpecified {
            get {
                return this.cantidadDiscapacitadosFieldSpecified;
            }
            set {
                this.cantidadDiscapacitadosFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fna.gov.co/esb/services/bancoproyectos/crearestructurainmobiliaria/v1")]
    public partial class ClasificacionParqueo_Crear : ClasificacionParqueo {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ComposicionGeneralInmobiliario_Crear))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fna.gov.co/cim/businessentities/composiciongeneralinmobiliario")]
    public partial class ComposicionGeneralInmobiliario {
        
        private int cantidadLotesField;
        
        private bool cantidadLotesFieldSpecified;
        
        private int cantidadManzanasField;
        
        private bool cantidadManzanasFieldSpecified;
        
        private int cantidadTorresField;
        
        private bool cantidadTorresFieldSpecified;
        
        private int cantidadBloquesField;
        
        private bool cantidadBloquesFieldSpecified;
        
        private int cantidadPisosField;
        
        private bool cantidadPisosFieldSpecified;
        
        private int cantidadDepositosField;
        
        private bool cantidadDepositosFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cantidadLotes {
            get {
                return this.cantidadLotesField;
            }
            set {
                this.cantidadLotesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cantidadLotesSpecified {
            get {
                return this.cantidadLotesFieldSpecified;
            }
            set {
                this.cantidadLotesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cantidadManzanas {
            get {
                return this.cantidadManzanasField;
            }
            set {
                this.cantidadManzanasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cantidadManzanasSpecified {
            get {
                return this.cantidadManzanasFieldSpecified;
            }
            set {
                this.cantidadManzanasFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cantidadTorres {
            get {
                return this.cantidadTorresField;
            }
            set {
                this.cantidadTorresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cantidadTorresSpecified {
            get {
                return this.cantidadTorresFieldSpecified;
            }
            set {
                this.cantidadTorresFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cantidadBloques {
            get {
                return this.cantidadBloquesField;
            }
            set {
                this.cantidadBloquesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cantidadBloquesSpecified {
            get {
                return this.cantidadBloquesFieldSpecified;
            }
            set {
                this.cantidadBloquesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cantidadPisos {
            get {
                return this.cantidadPisosField;
            }
            set {
                this.cantidadPisosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cantidadPisosSpecified {
            get {
                return this.cantidadPisosFieldSpecified;
            }
            set {
                this.cantidadPisosFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cantidadDepositos {
            get {
                return this.cantidadDepositosField;
            }
            set {
                this.cantidadDepositosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cantidadDepositosSpecified {
            get {
                return this.cantidadDepositosFieldSpecified;
            }
            set {
                this.cantidadDepositosFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fna.gov.co/esb/services/bancoproyectos/crearestructurainmobiliaria/v1")]
    public partial class ComposicionGeneralInmobiliario_Crear : ComposicionGeneralInmobiliario {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ClasificacionInmueble_Crear))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fna.gov.co/cim/businessentities/clasificacioninmueble")]
    public partial class ClasificacionInmueble {
        
        private int cantidadCasasField;
        
        private bool cantidadCasasFieldSpecified;
        
        private int cantidadCasasBifamiliariasField;
        
        private bool cantidadCasasBifamiliariasFieldSpecified;
        
        private int cantidadApartamentosField;
        
        private bool cantidadApartamentosFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cantidadCasas {
            get {
                return this.cantidadCasasField;
            }
            set {
                this.cantidadCasasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cantidadCasasSpecified {
            get {
                return this.cantidadCasasFieldSpecified;
            }
            set {
                this.cantidadCasasFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cantidadCasasBifamiliarias {
            get {
                return this.cantidadCasasBifamiliariasField;
            }
            set {
                this.cantidadCasasBifamiliariasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cantidadCasasBifamiliariasSpecified {
            get {
                return this.cantidadCasasBifamiliariasFieldSpecified;
            }
            set {
                this.cantidadCasasBifamiliariasFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cantidadApartamentos {
            get {
                return this.cantidadApartamentosField;
            }
            set {
                this.cantidadApartamentosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cantidadApartamentosSpecified {
            get {
                return this.cantidadApartamentosFieldSpecified;
            }
            set {
                this.cantidadApartamentosFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fna.gov.co/esb/services/bancoproyectos/crearestructurainmobiliaria/v1")]
    public partial class ClasificacionInmueble_Crear : ClasificacionInmueble {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InventarioViviendas_Crear))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fna.gov.co/cim/businessentities/inventarioviviendas")]
    public partial class InventarioViviendas {
        
        private int viviendasInteresPrioritarioField;
        
        private bool viviendasInteresPrioritarioFieldSpecified;
        
        private int viviendasInteresSocialField;
        
        private bool viviendasInteresSocialFieldSpecified;
        
        private int viviendasInteresNormalField;
        
        private bool viviendasInteresNormalFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int viviendasInteresPrioritario {
            get {
                return this.viviendasInteresPrioritarioField;
            }
            set {
                this.viviendasInteresPrioritarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool viviendasInteresPrioritarioSpecified {
            get {
                return this.viviendasInteresPrioritarioFieldSpecified;
            }
            set {
                this.viviendasInteresPrioritarioFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int viviendasInteresSocial {
            get {
                return this.viviendasInteresSocialField;
            }
            set {
                this.viviendasInteresSocialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool viviendasInteresSocialSpecified {
            get {
                return this.viviendasInteresSocialFieldSpecified;
            }
            set {
                this.viviendasInteresSocialFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int viviendasInteresNormal {
            get {
                return this.viviendasInteresNormalField;
            }
            set {
                this.viviendasInteresNormalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool viviendasInteresNormalSpecified {
            get {
                return this.viviendasInteresNormalFieldSpecified;
            }
            set {
                this.viviendasInteresNormalFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fna.gov.co/esb/services/bancoproyectos/crearestructurainmobiliaria/v1")]
    public partial class InventarioViviendas_Crear : InventarioViviendas {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InformacionEstructuraInmobiliaria_Crear))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fna.gov.co/cim/businessentities/informacionestructurainmobiliaria")]
    public partial class InformacionEstructuraInmobiliaria {
        
        private int idEstructuraField;
        
        private bool idEstructuraFieldSpecified;
        
        private InventarioViviendas inventarioViviendasPorEstructuraField;
        
        private ClasificacionInmueble clasificacionInmuebleEstructuraField;
        
        private ComposicionGeneralInmobiliario composicionGeneralEstructuraField;
        
        private ClasificacionParqueo clasificacionParqueoEstructuraField;
        
        private DetalleAreaLote detalleAreaLoteEstructuraField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idEstructura {
            get {
                return this.idEstructuraField;
            }
            set {
                this.idEstructuraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idEstructuraSpecified {
            get {
                return this.idEstructuraFieldSpecified;
            }
            set {
                this.idEstructuraFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InventarioViviendas inventarioViviendasPorEstructura {
            get {
                return this.inventarioViviendasPorEstructuraField;
            }
            set {
                this.inventarioViviendasPorEstructuraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClasificacionInmueble clasificacionInmuebleEstructura {
            get {
                return this.clasificacionInmuebleEstructuraField;
            }
            set {
                this.clasificacionInmuebleEstructuraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ComposicionGeneralInmobiliario composicionGeneralEstructura {
            get {
                return this.composicionGeneralEstructuraField;
            }
            set {
                this.composicionGeneralEstructuraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClasificacionParqueo clasificacionParqueoEstructura {
            get {
                return this.clasificacionParqueoEstructuraField;
            }
            set {
                this.clasificacionParqueoEstructuraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DetalleAreaLote detalleAreaLoteEstructura {
            get {
                return this.detalleAreaLoteEstructuraField;
            }
            set {
                this.detalleAreaLoteEstructuraField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fna.gov.co/esb/services/bancoproyectos/crearestructurainmobiliaria/v1")]
    public partial class InformacionEstructuraInmobiliaria_Crear : InformacionEstructuraInmobiliaria {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fna.gov.co/esb/services/bancoproyectos/crearestructurainmobiliaria/v1")]
    public partial class ServiceRequest {
        
        private int idProyectoField;
        
        private InformacionEstructuraInmobiliaria_Crear informacionEstructuraInmobiliariaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idProyecto {
            get {
                return this.idProyectoField;
            }
            set {
                this.idProyectoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InformacionEstructuraInmobiliaria_Crear informacionEstructuraInmobiliaria {
            get {
                return this.informacionEstructuraInmobiliariaField;
            }
            set {
                this.informacionEstructuraInmobiliariaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fna.gov.co/esb/services/cl/consumerheader")]
    public partial class Property {
        
        private string keyField;
        
        private string typeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fna.gov.co/esb/services/cl/consumerheader")]
    public partial class Destination {
        
        private string nameField;
        
        private string namespaceField;
        
        private string operationField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="anyURI")]
        public string @namespace {
            get {
                return this.namespaceField;
            }
            set {
                this.namespaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string operation {
            get {
                return this.operationField;
            }
            set {
                this.operationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void CrearEstructuraInmobiliariaCompletedEventHandler(object sender, CrearEstructuraInmobiliariaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CrearEstructuraInmobiliariaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CrearEstructuraInmobiliariaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServicioResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServicioResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591