//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 



public class InfoCasoDesembolso {
    
    private M_DesembolsoOidTrackingDesembolso oidTrackingDesembolsoField;
    
    private string sNumeroTramiteField;
    
    /// <remarks/>
    public M_DesembolsoOidTrackingDesembolso OidTrackingDesembolso {
        get {

            if (this.oidTrackingDesembolsoField == null)
                this.oidTrackingDesembolsoField = new M_DesembolsoOidTrackingDesembolso();
            return this.oidTrackingDesembolsoField;
        }
        set {
            this.oidTrackingDesembolsoField = value;
        }
    }
    
    /// <remarks/>
    public string SNumeroTramite {
        get {
            return this.sNumeroTramiteField;
        }
        set {
            this.sNumeroTramiteField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class M_DesembolsoOidTrackingDesembolso {
    
    private string iIdCasoField;
    
    private string sNombreUsuarioEstacionField;
    
    private string sCodigoEstacionField;
    
    private string iRutaField;
    
    private M_DesembolsoOidTrackingDesembolsoOidTipoDocumentoEstac oidTipoDocumentoEstacField;
    
    private string sIdentificacionEstacionField;
    
    private M_DesembolsoOidTrackingDesembolsoOidActividadEspera oidActividadEsperaField;
    
    private string iEtapaField;
    
    private string entityNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string IIdCaso {
        get {
            return this.iIdCasoField;
        }
        set {
            this.iIdCasoField = value;
        }
    }
    
    /// <remarks/>
    public string SNombreUsuarioEstacion {
        get {
            return this.sNombreUsuarioEstacionField;
        }
        set {
            this.sNombreUsuarioEstacionField = value;
        }
    }
    
    /// <remarks/>
    public string SCodigoEstacion {
        get {
            return this.sCodigoEstacionField;
        }
        set {
            this.sCodigoEstacionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string IRuta {
        get {
            return this.iRutaField;
        }
        set {
            this.iRutaField = value;
        }
    }
    
    /// <remarks/>
    public M_DesembolsoOidTrackingDesembolsoOidTipoDocumentoEstac OidTipoDocumentoEstac {
        get {
            if (this.oidTipoDocumentoEstacField == null)
                this.oidTipoDocumentoEstacField = new M_DesembolsoOidTrackingDesembolsoOidTipoDocumentoEstac();
            return this.oidTipoDocumentoEstacField;
        }
        set {
            this.oidTipoDocumentoEstacField = value;
        }
    }
    
    /// <remarks/>
    public string SIdentificacionEstacion {
        get {
            return this.sIdentificacionEstacionField;
        }
        set {
            this.sIdentificacionEstacionField = value;
        }
    }
    
    /// <remarks/>
    public M_DesembolsoOidTrackingDesembolsoOidActividadEspera OidActividadEspera {
        get {
            if (this.oidActividadEsperaField == null)
                this.oidActividadEsperaField = new M_DesembolsoOidTrackingDesembolsoOidActividadEspera();
            return this.oidActividadEsperaField;
        }
        set {
            this.oidActividadEsperaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string IEtapa {
        get {
            return this.iEtapaField;
        }
        set {
            this.iEtapaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string entityName {
        get {
            return this.entityNameField;
        }
        set {
            this.entityNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class M_DesembolsoOidTrackingDesembolsoOidTipoDocumentoEstac {
    
    private string sCodigoField;
    
    private string entityNameField;
    
    /// <remarks/>
    public string SCodigo {
        get {
            return this.sCodigoField;
        }
        set {
            this.sCodigoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string entityName {
        get {
            return this.entityNameField;
        }
        set {
            this.entityNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class M_DesembolsoOidTrackingDesembolsoOidActividadEspera {
    
    private string sTransformacionField;
    
    private M_DesembolsoOidTrackingDesembolsoOidActividadEsperaOidProceso oidProcesoField;
    
    private string sTaskNameField;
    
    private string entityNameField;
    
    /// <remarks/>
    public string STransformacion {
        get {
            return this.sTransformacionField;
        }
        set {
            this.sTransformacionField = value;
        }
    }
    
    /// <remarks/>
    public M_DesembolsoOidTrackingDesembolsoOidActividadEsperaOidProceso OidProceso {
        get {
            if (this.oidProcesoField == null)
                this.oidProcesoField = new M_DesembolsoOidTrackingDesembolsoOidActividadEsperaOidProceso();
            return this.oidProcesoField;
        }
        set {
            this.oidProcesoField = value;
        }
    }
    
    /// <remarks/>
    public string STaskName {
        get {
            return this.sTaskNameField;
        }
        set {
            this.sTaskNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string entityName {
        get {
            return this.entityNameField;
        }
        set {
            this.entityNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class M_DesembolsoOidTrackingDesembolsoOidActividadEsperaOidProceso {
    
    private string sNombreTecnicoField;
    
    private string entityNameField;
    
    /// <remarks/>
    public string SNombreTecnico {
        get {
            return this.sNombreTecnicoField;
        }
        set {
            this.sNombreTecnicoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string entityName {
        get {
            return this.entityNameField;
        }
        set {
            this.entityNameField = value;
        }
    }
}
