//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class M_CAT_GestionDesembolso
{

    private M_CAT_GestionDesembolsoOidInformacionDesembolso oidInformacionDesembolsoField;

    /// <remarks/>
    public M_CAT_GestionDesembolsoOidInformacionDesembolso OidInformacionDesembolso
    {
        get
        {
            if (oidInformacionDesembolsoField == null)
                oidInformacionDesembolsoField = new M_CAT_GestionDesembolsoOidInformacionDesembolso();
            return this.oidInformacionDesembolsoField;
        }
        set
        {
            this.oidInformacionDesembolsoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class M_CAT_GestionDesembolsoOidInformacionDesembolso
{
    private M_CAT_GestionDesembolsoOidInformacionDesembolsoOidFormaDesembolso oidFormaDesembolsoField;


    private M_CAT_GestionDesembolsoOidInformacionDesembolsoOidEstadoDesembolso oidEstadoDesembolsoField;

    private decimal cMontoField;

    private bool cMontoFieldSpecified;

    private M_CAT_GestionDesembolsoOidInformacionDesembolsoOidTrackingDesembolso oidTrackingDesembolsoField;

    private string sNumeroTramiteField;

    private List<M_CAT_GestionDesembolsoOidInformacionDesembolsoXOrdenesPagoM_OrdenPago> xOrdenesPagoField;

    private string entityNameField;

    /// <remarks/>
    public M_CAT_GestionDesembolsoOidInformacionDesembolsoOidFormaDesembolso OidFormaDesembolso
    {
        get
        {
            if (oidFormaDesembolsoField == null)
                oidFormaDesembolsoField = new M_CAT_GestionDesembolsoOidInformacionDesembolsoOidFormaDesembolso();
            return this.oidFormaDesembolsoField;
        }
        set
        {
            this.oidFormaDesembolsoField = value;
        }
    }



    /// <remarks/>
    public M_CAT_GestionDesembolsoOidInformacionDesembolsoOidEstadoDesembolso OidEstadoDesembolso
    {
        get
        {
            if (oidEstadoDesembolsoField == null)
                oidEstadoDesembolsoField = new M_CAT_GestionDesembolsoOidInformacionDesembolsoOidEstadoDesembolso();
            return this.oidEstadoDesembolsoField;
        }
        set
        {
            this.oidEstadoDesembolsoField = value;
        }
    }

    /// <remarks/>
    public decimal CMonto
    {
        get
        {
            return this.cMontoField;
        }
        set
        {
            this.cMontoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CMontoSpecified
    {
        get
        {
            return this.cMontoFieldSpecified;
        }
        set
        {
            this.cMontoFieldSpecified = value;
        }
    }

    /// <remarks/>
    public M_CAT_GestionDesembolsoOidInformacionDesembolsoOidTrackingDesembolso OidTrackingDesembolso
    {
        get
        {
            if (oidTrackingDesembolsoField == null)
                oidTrackingDesembolsoField = new M_CAT_GestionDesembolsoOidInformacionDesembolsoOidTrackingDesembolso();
            return this.oidTrackingDesembolsoField;
        }
        set
        {
            this.oidTrackingDesembolsoField = value;
        }
    }

    /// <remarks/>
    public string SNumeroTramite
    {
        get
        {
            return this.sNumeroTramiteField;
        }
        set
        {
            this.sNumeroTramiteField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("M_OrdenPago", typeof(M_CAT_GestionDesembolsoOidInformacionDesembolsoXOrdenesPagoM_OrdenPago), IsNullable = false)]
    public List<M_CAT_GestionDesembolsoOidInformacionDesembolsoXOrdenesPagoM_OrdenPago> XOrdenesPago
    {
        get
        {
            if (xOrdenesPagoField == null)
                xOrdenesPagoField = new List<M_CAT_GestionDesembolsoOidInformacionDesembolsoXOrdenesPagoM_OrdenPago>();
            return this.xOrdenesPagoField;
        }
        set
        {
            this.xOrdenesPagoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string entityName
    {
        get
        {
            return this.entityNameField;
        }
        set
        {
            this.entityNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class M_CAT_GestionDesembolsoOidInformacionDesembolsoOidFormaDesembolso
{

    private string sCodigoField;

    private string entityNameField;

    /// <remarks/>
    public string SCodigo
    {
        get
        {
            return this.sCodigoField;
        }
        set
        {
            this.sCodigoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string entityName
    {
        get
        {
            return this.entityNameField;
        }
        set
        {
            this.entityNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class M_CAT_GestionDesembolsoOidInformacionDesembolsoOidEstadoDesembolso
{

    private string sCodigoField;

    private string entityNameField;

    /// <remarks/>
    public string SCodigo
    {
        get
        {
            return this.sCodigoField;
        }
        set
        {
            this.sCodigoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string entityName
    {
        get
        {
            return this.entityNameField;
        }
        set
        {
            this.entityNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class M_CAT_GestionDesembolsoOidInformacionDesembolsoOidTrackingDesembolso
{
    private List<M_CAT_GestionDesembolsoOidInformacionDesembolsoOidTrackingDesembolsoXCausalesDevolucionM_CausalesDevolucion> xCausalesDevolucionField;

    private System.DateTime dFechaNotificacionField;

    private bool dFechaNotificacionFieldSpecified;

    private M_CAT_GestionDesembolsoOidInformacionDesembolsoOidTrackingDesembolsoOidCausalRechazoDesembolso oidCausalRechazoDesembolsoField;

    private string sCodigoEstacionField;

    private string iRutaField;

    private M_CAT_GestionDesembolsoOidInformacionDesembolsoOidTrackingDesembolsoOidTipoDocumentoEstac oidTipoDocumentoEstacField;

    private M_CAT_GestionDesembolsoOidInformacionDesembolsoOidTrackingDesembolsoOidCausalReintegro oidCausalReintegroField;

    private string sIdentificacionEstacionField;

    private string iEtapaField;

    private List<M_CAT_GestionDesembolsoOidInformacionDesembolsoOidTrackingDesembolsoXCausalesPNCM_CausalesPNC> xCausalesPNCField;

    private string entityNameField;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("M_CausalesDevolucion", typeof(M_CAT_GestionDesembolsoOidInformacionDesembolsoOidTrackingDesembolsoXCausalesDevolucionM_CausalesDevolucion), IsNullable = false)]
    public List<M_CAT_GestionDesembolsoOidInformacionDesembolsoOidTrackingDesembolsoXCausalesDevolucionM_CausalesDevolucion> XCausalesDevolucion
    {
        get
        {
            if (xCausalesDevolucionField == null)
                xCausalesDevolucionField = new List<M_CAT_GestionDesembolsoOidInformacionDesembolsoOidTrackingDesembolsoXCausalesDevolucionM_CausalesDevolucion>();
            return this.xCausalesDevolucionField;
        }
        set
        {
            this.xCausalesDevolucionField = value;
        }
    }

    /// <remarks/>
    public System.DateTime DFechaNotificacion
    {
        get
        {
            return this.dFechaNotificacionField;
        }
        set
        {
            this.dFechaNotificacionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DFechaNotificacionSpecified
    {
        get
        {
            return this.dFechaNotificacionFieldSpecified;
        }
        set
        {
            this.dFechaNotificacionFieldSpecified = value;
        }
    }

    /// <remarks/>
    public M_CAT_GestionDesembolsoOidInformacionDesembolsoOidTrackingDesembolsoOidCausalRechazoDesembolso OidCausalRechazoDesembolso
    {
        get
        {
            if (oidCausalRechazoDesembolsoField == null)
                oidCausalRechazoDesembolsoField = new M_CAT_GestionDesembolsoOidInformacionDesembolsoOidTrackingDesembolsoOidCausalRechazoDesembolso();
            return this.oidCausalRechazoDesembolsoField;
        }
        set
        {
            this.oidCausalRechazoDesembolsoField = value;
        }
    }

    /// <remarks/>
    public string SCodigoEstacion
    {
        get
        {
            return this.sCodigoEstacionField;
        }
        set
        {
            this.sCodigoEstacionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
    public string IRuta
    {
        get
        {
            return this.iRutaField;
        }
        set
        {
            this.iRutaField = value;
        }
    }

    /// <remarks/>
    public M_CAT_GestionDesembolsoOidInformacionDesembolsoOidTrackingDesembolsoOidTipoDocumentoEstac OidTipoDocumentoEstac
    {
        get
        {
            if (oidTipoDocumentoEstacField == null)
                oidTipoDocumentoEstacField = new M_CAT_GestionDesembolsoOidInformacionDesembolsoOidTrackingDesembolsoOidTipoDocumentoEstac();
            return this.oidTipoDocumentoEstacField;
        }
        set
        {
            this.oidTipoDocumentoEstacField = value;
        }
    }

    /// <remarks/>
    public M_CAT_GestionDesembolsoOidInformacionDesembolsoOidTrackingDesembolsoOidCausalReintegro OidCausalReintegro
    {
        get
        {
            if (oidCausalReintegroField == null)
                oidCausalReintegroField = new M_CAT_GestionDesembolsoOidInformacionDesembolsoOidTrackingDesembolsoOidCausalReintegro();
            return this.oidCausalReintegroField;
        }
        set
        {
            this.oidCausalReintegroField = value;
        }
    }

    /// <remarks/>
    public string SIdentificacionEstacion
    {
        get
        {
            return this.sIdentificacionEstacionField;
        }
        set
        {
            this.sIdentificacionEstacionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
    public string IEtapa
    {
        get
        {
            return this.iEtapaField;
        }
        set
        {
            this.iEtapaField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("M_CausalesPNC", typeof(M_CAT_GestionDesembolsoOidInformacionDesembolsoOidTrackingDesembolsoXCausalesPNCM_CausalesPNC), IsNullable = false)]
    public List<M_CAT_GestionDesembolsoOidInformacionDesembolsoOidTrackingDesembolsoXCausalesPNCM_CausalesPNC> XCausalesPNC
    {
        get
        {
            if (xCausalesPNCField == null)
                xCausalesPNCField = new List<M_CAT_GestionDesembolsoOidInformacionDesembolsoOidTrackingDesembolsoXCausalesPNCM_CausalesPNC>();
            return this.xCausalesPNCField;
        }
        set
        {
            this.xCausalesPNCField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string entityName
    {
        get
        {
            return this.entityNameField;
        }
        set
        {
            this.entityNameField = value;
        }
    }
}


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class M_CAT_GestionDesembolsoOidInformacionDesembolsoOidTrackingDesembolsoXCausalesDevolucionM_CausalesDevolucion
{

    private M_CAT_GestionDesembolsoOidInformacionDesembolsoOidTrackingDesembolsoXCausalesDevolucionM_CausalesDevolucionOidCausalDevolucion oidCausalDevolucionField;

    /// <remarks/>
    public M_CAT_GestionDesembolsoOidInformacionDesembolsoOidTrackingDesembolsoXCausalesDevolucionM_CausalesDevolucionOidCausalDevolucion OidCausalDevolucion
    {
        get
        {
            if (oidCausalDevolucionField == null)
                oidCausalDevolucionField = new M_CAT_GestionDesembolsoOidInformacionDesembolsoOidTrackingDesembolsoXCausalesDevolucionM_CausalesDevolucionOidCausalDevolucion();
            return this.oidCausalDevolucionField;
        }
        set
        {
            this.oidCausalDevolucionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class M_CAT_GestionDesembolsoOidInformacionDesembolsoOidTrackingDesembolsoXCausalesDevolucionM_CausalesDevolucionOidCausalDevolucion
{

    private string sCodigoField;

    private string entityNameField;

    /// <remarks/>
    public string SCodigo
    {
        get
        {
            return this.sCodigoField;
        }
        set
        {
            this.sCodigoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string entityName
    {
        get
        {
            return this.entityNameField;
        }
        set
        {
            this.entityNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class M_CAT_GestionDesembolsoOidInformacionDesembolsoOidTrackingDesembolsoOidCausalRechazoDesembolso
{

    private string sCodigoField;

    private string entityNameField;

    /// <remarks/>
    public string SCodigo
    {
        get
        {
            return this.sCodigoField;
        }
        set
        {
            this.sCodigoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string entityName
    {
        get
        {
            return this.entityNameField;
        }
        set
        {
            this.entityNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class M_CAT_GestionDesembolsoOidInformacionDesembolsoOidTrackingDesembolsoOidTipoDocumentoEstac
{

    private string sCodigoField;

    private string entityNameField;

    /// <remarks/>
    public string SCodigo
    {
        get
        {
            return this.sCodigoField;
        }
        set
        {
            this.sCodigoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string entityName
    {
        get
        {
            return this.entityNameField;
        }
        set
        {
            this.entityNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class M_CAT_GestionDesembolsoOidInformacionDesembolsoOidTrackingDesembolsoOidCausalReintegro
{

    private string sCodigoField;

    private string entityNameField;

    /// <remarks/>
    public string SCodigo
    {
        get
        {
            return this.sCodigoField;
        }
        set
        {
            this.sCodigoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string entityName
    {
        get
        {
            return this.entityNameField;
        }
        set
        {
            this.entityNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class M_CAT_GestionDesembolsoOidInformacionDesembolsoOidTrackingDesembolsoXCausalesPNCM_CausalesPNC
{

    private M_CAT_GestionDesembolsoOidInformacionDesembolsoOidTrackingDesembolsoXCausalesPNCM_CausalesPNCOidCausalPNC oidCausalPNCField;

    /// <remarks/>
    public M_CAT_GestionDesembolsoOidInformacionDesembolsoOidTrackingDesembolsoXCausalesPNCM_CausalesPNCOidCausalPNC OidCausalPNC
    {
        get
        {
            if (oidCausalPNCField == null)
                oidCausalPNCField = new M_CAT_GestionDesembolsoOidInformacionDesembolsoOidTrackingDesembolsoXCausalesPNCM_CausalesPNCOidCausalPNC();
            return this.oidCausalPNCField;
        }
        set
        {
            this.oidCausalPNCField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class M_CAT_GestionDesembolsoOidInformacionDesembolsoOidTrackingDesembolsoXCausalesPNCM_CausalesPNCOidCausalPNC
{

    private string sCodigoField;

    private string entityNameField;

    /// <remarks/>
    public string SCodigo
    {
        get
        {
            return this.sCodigoField;
        }
        set
        {
            this.sCodigoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string entityName
    {
        get
        {
            return this.entityNameField;
        }
        set
        {
            this.entityNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class M_CAT_GestionDesembolsoOidInformacionDesembolsoXOrdenesPagoM_OrdenPago
{

    private string sNumeroOrdenPagoField;

    private M_CAT_GestionDesembolsoOidInformacionDesembolsoXOrdenesPagoM_OrdenPagoOidEstadoOrdenPago oidEstadoOrdenPagoField;

    /// <remarks/>
    public string SNumeroOrdenPago
    {
        get
        {
            return this.sNumeroOrdenPagoField;
        }
        set
        {
            this.sNumeroOrdenPagoField = value;
        }
    }

    /// <remarks/>
    public M_CAT_GestionDesembolsoOidInformacionDesembolsoXOrdenesPagoM_OrdenPagoOidEstadoOrdenPago OidEstadoOrdenPago
    {
        get
        {
            if (oidEstadoOrdenPagoField == null)
                oidEstadoOrdenPagoField = new M_CAT_GestionDesembolsoOidInformacionDesembolsoXOrdenesPagoM_OrdenPagoOidEstadoOrdenPago();
            return this.oidEstadoOrdenPagoField;
        }
        set
        {
            this.oidEstadoOrdenPagoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class M_CAT_GestionDesembolsoOidInformacionDesembolsoXOrdenesPagoM_OrdenPagoOidEstadoOrdenPago
{

    private string sCodigoField;

    private string entityNameField;

    /// <remarks/>
    public string SCodigo
    {
        get
        {
            return this.sCodigoField;
        }
        set
        {
            this.sCodigoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string entityName
    {
        get
        {
            return this.entityNameField;
        }
        set
        {
            this.entityNameField = value;
        }
    }
}
