//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8745
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class M_Solicitud {
    
    private M_SolicitudOidReclamacionSeguro oidReclamacionSeguroField;
    
    /// <remarks/>
    public M_SolicitudOidReclamacionSeguro OidReclamacionSeguro {
        get {
            return this.oidReclamacionSeguroField;
        }
        set {
            this.oidReclamacionSeguroField = value;
        }
    }

    private sbyte keyField;

    private bool keyFieldSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte key
    {
        get
        {
            return this.keyField;
        }
        set
        {
            this.keyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool keySpecified
    {
        get
        {
            return this.keyFieldSpecified;
        }
        set
        {
            this.keyFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class M_SolicitudOidReclamacionSeguro {
    
    private List<M_SolicitudOidReclamacionSeguroXDocumentosReclamacionM_DocumentoRecSeguro> xDocumentosReclamacionField;
    
    private string entityNameField;

    private sbyte keyField;

    private bool keyFieldSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("M_DocumentoRecSeguro", typeof(M_SolicitudOidReclamacionSeguroXDocumentosReclamacionM_DocumentoRecSeguro), IsNullable=false)]
    public List<M_SolicitudOidReclamacionSeguroXDocumentosReclamacionM_DocumentoRecSeguro> XDocumentosReclamacion {
        get {
            return this.xDocumentosReclamacionField;
        }
        set {
            this.xDocumentosReclamacionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string entityName {
        get {
            return this.entityNameField;
        }
        set {
            this.entityNameField = value;
        }
    }


    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte key
    {
        get
        {
            return this.keyField;
        }
        set
        {
            this.keyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool keySpecified
    {
        get
        {
            return this.keyFieldSpecified;
        }
        set
        {
            this.keyFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class M_SolicitudOidReclamacionSeguroXDocumentosReclamacionM_DocumentoRecSeguro {
    
    private M_SolicitudOidReclamacionSeguroXDocumentosReclamacionM_DocumentoRecSeguroOidDocumento oidDocumentoField;
    
    private string sUrlDocumentoField;
    
    /// <remarks/>
    public M_SolicitudOidReclamacionSeguroXDocumentosReclamacionM_DocumentoRecSeguroOidDocumento OidDocumento {
        get {
            return this.oidDocumentoField;
        }
        set {
            this.oidDocumentoField = value;
        }
    }
    
    /// <remarks/>
    public string SUrlDocumento {
        get {
            return this.sUrlDocumentoField;
        }
        set {
            this.sUrlDocumentoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class M_SolicitudOidReclamacionSeguroXDocumentosReclamacionM_DocumentoRecSeguroOidDocumento {
    
    private M_SolicitudOidReclamacionSeguroXDocumentosReclamacionM_DocumentoRecSeguroOidDocumentoOidTipoDocumento oidTipoDocumentoField;
    
    private M_SolicitudOidReclamacionSeguroXDocumentosReclamacionM_DocumentoRecSeguroOidDocumentoOidTipoRamo oidTipoRamoField;
    
    private string entityNameField;
    
    /// <remarks/>
    public M_SolicitudOidReclamacionSeguroXDocumentosReclamacionM_DocumentoRecSeguroOidDocumentoOidTipoDocumento OidTipoDocumento {
        get {
            return this.oidTipoDocumentoField;
        }
        set {
            this.oidTipoDocumentoField = value;
        }
    }
    
    /// <remarks/>
    public M_SolicitudOidReclamacionSeguroXDocumentosReclamacionM_DocumentoRecSeguroOidDocumentoOidTipoRamo OidTipoRamo {
        get {
            return this.oidTipoRamoField;
        }
        set {
            this.oidTipoRamoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string entityName {
        get {
            return this.entityNameField;
        }
        set {
            this.entityNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class M_SolicitudOidReclamacionSeguroXDocumentosReclamacionM_DocumentoRecSeguroOidDocumentoOidTipoDocumento {
    
    private string sCodigoField;
    
    private string entityNameField;
    
    /// <remarks/>
    public string SCodigo {
        get {
            return this.sCodigoField;
        }
        set {
            this.sCodigoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string entityName {
        get {
            return this.entityNameField;
        }
        set {
            this.entityNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class M_SolicitudOidReclamacionSeguroXDocumentosReclamacionM_DocumentoRecSeguroOidDocumentoOidTipoRamo {
    
    private string sCodigoField;
    
    private string entityNameField;
    
    /// <remarks/>
    public string SCodigo {
        get {
            return this.sCodigoField;
        }
        set {
            this.sCodigoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string entityName {
        get {
            return this.entityNameField;
        }
        set {
            this.entityNameField = value;
        }
    }
}
