//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Bizagi.Proxy.Layer.BancoProyectos.CrearProyectoInmob.CrearProyectoInmob {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BancoProyectos_CrearProyectoInmobiliario_Binding12", Namespace="http://www.fna.gov.co/esb/services/bancoproyectos/crearproyectoinmobiliario/v1")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InformacionProyectoInmobiliario))]
    public partial class BancoProyectos_CrearProyectoInmobiliario_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private ConsumerHeader consumerHeaderField;
        
        private System.Threading.SendOrPostCallback CrearProyectoInmobiliarioOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BancoProyectos_CrearProyectoInmobiliario_Service() {
            this.SoapVersion = System.Web.Services.Protocols.SoapProtocolVersion.Soap12;
            this.Url = global::Bizagi.Proxy.Layer.BancoProyectos.CrearProyectoInmob.Properties.Settings.Default.Bizagi_Proxy_Layer_BancoProyectos_CrearProyectoInmob_CrearProyectoInmob_BancoProyectos_CrearProyectoInmobiliario_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public ConsumerHeader consumerHeader {
            get {
                return this.consumerHeaderField;
            }
            set {
                this.consumerHeaderField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CrearProyectoInmobiliarioCompletedEventHandler CrearProyectoInmobiliarioCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("consumerHeader")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("CrearProyectoInmobiliario", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("CrearProyectoInmobiliarioResponse", Namespace="http://www.fna.gov.co/esb/services/bancoproyectos/crearproyectoinmobiliario/v1")]
        public ServicioResponse CrearProyectoInmobiliario([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.fna.gov.co/esb/services/bancoproyectos/crearproyectoinmobiliario/v1")] ServiceRequest CrearProyectoInmobiliarioRequest) {
            object[] results = this.Invoke("CrearProyectoInmobiliario", new object[] {
                        CrearProyectoInmobiliarioRequest});
            return ((ServicioResponse)(results[0]));
        }
        
        /// <remarks/>
        public void CrearProyectoInmobiliarioAsync(ServiceRequest CrearProyectoInmobiliarioRequest) {
            this.CrearProyectoInmobiliarioAsync(CrearProyectoInmobiliarioRequest, null);
        }
        
        /// <remarks/>
        public void CrearProyectoInmobiliarioAsync(ServiceRequest CrearProyectoInmobiliarioRequest, object userState) {
            if ((this.CrearProyectoInmobiliarioOperationCompleted == null)) {
                this.CrearProyectoInmobiliarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCrearProyectoInmobiliarioOperationCompleted);
            }
            this.InvokeAsync("CrearProyectoInmobiliario", new object[] {
                        CrearProyectoInmobiliarioRequest}, this.CrearProyectoInmobiliarioOperationCompleted, userState);
        }
        
        private void OnCrearProyectoInmobiliarioOperationCompleted(object arg) {
            if ((this.CrearProyectoInmobiliarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CrearProyectoInmobiliarioCompleted(this, new CrearProyectoInmobiliarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fna.gov.co/esb/services/cl/consumerheader")]
    [System.Xml.Serialization.XmlRootAttribute("consumerHeader", Namespace="http://www.fna.gov.co/esb/services/cl/consumerheader", IsNullable=false)]
    public partial class ConsumerHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string systemIdField;
        
        private string clientTransactionIDField;
        
        private string endHostField;
        
        private string endUserField;
        
        private System.DateTime datetimeField;
        
        private bool datetimeFieldSpecified;
        
        private RequestData requestDataField;
        
        private Property[] messageContextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string systemId {
            get {
                return this.systemIdField;
            }
            set {
                this.systemIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string clientTransactionID {
            get {
                return this.clientTransactionIDField;
            }
            set {
                this.clientTransactionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string endHost {
            get {
                return this.endHostField;
            }
            set {
                this.endHostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string endUser {
            get {
                return this.endUserField;
            }
            set {
                this.endUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime datetime {
            get {
                return this.datetimeField;
            }
            set {
                this.datetimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool datetimeSpecified {
            get {
                return this.datetimeFieldSpecified;
            }
            set {
                this.datetimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RequestData requestData {
            get {
                return this.requestDataField;
            }
            set {
                this.requestDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("property", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Property[] messageContext {
            get {
                return this.messageContextField;
            }
            set {
                this.messageContextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fna.gov.co/esb/services/cl/consumerheader")]
    public partial class RequestData {
        
        private UserId userIdField;
        
        private Destination destinationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UserId userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Destination destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fna.gov.co/esb/services/cl/consumerheader")]
    public partial class UserId {
        
        private string userNameField;
        
        private string userTokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userToken {
            get {
                return this.userTokenField;
            }
            set {
                this.userTokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fna.gov.co/esb/services/bancoproyectos/crearproyectoinmobiliario/v1")]
    public partial class ServicioResponse {
        
        private int idProyectoField;
        
        private int numeroProyectoField;
        
        private bool numeroProyectoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idProyecto {
            get {
                return this.idProyectoField;
            }
            set {
                this.idProyectoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int numeroProyecto {
            get {
                return this.numeroProyectoField;
            }
            set {
                this.numeroProyectoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroProyectoSpecified {
            get {
                return this.numeroProyectoFieldSpecified;
            }
            set {
                this.numeroProyectoFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DetalleAreaLote_Crear))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fna.gov.co/cim/businessentities/detallearealote")]
    public partial class DetalleAreaLote {
        
        private decimal areaBrutaField;
        
        private bool areaBrutaFieldSpecified;
        
        private decimal areaProteccionField;
        
        private bool areaProteccionFieldSpecified;
        
        private decimal areaAfectadaField;
        
        private bool areaAfectadaFieldSpecified;
        
        private decimal areaCesionField;
        
        private bool areaCesionFieldSpecified;
        
        private decimal areaUtilField;
        
        private bool areaUtilFieldSpecified;
        
        private decimal areaTotalConstruidaField;
        
        private bool areaTotalConstruidaFieldSpecified;
        
        private decimal areaConstruidaPrimerPisoField;
        
        private bool areaConstruidaPrimerPisoFieldSpecified;
        
        private decimal areaVendibleViviendaField;
        
        private bool areaVendibleViviendaFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal areaBruta {
            get {
                return this.areaBrutaField;
            }
            set {
                this.areaBrutaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool areaBrutaSpecified {
            get {
                return this.areaBrutaFieldSpecified;
            }
            set {
                this.areaBrutaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal areaProteccion {
            get {
                return this.areaProteccionField;
            }
            set {
                this.areaProteccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool areaProteccionSpecified {
            get {
                return this.areaProteccionFieldSpecified;
            }
            set {
                this.areaProteccionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal areaAfectada {
            get {
                return this.areaAfectadaField;
            }
            set {
                this.areaAfectadaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool areaAfectadaSpecified {
            get {
                return this.areaAfectadaFieldSpecified;
            }
            set {
                this.areaAfectadaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal areaCesion {
            get {
                return this.areaCesionField;
            }
            set {
                this.areaCesionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool areaCesionSpecified {
            get {
                return this.areaCesionFieldSpecified;
            }
            set {
                this.areaCesionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal areaUtil {
            get {
                return this.areaUtilField;
            }
            set {
                this.areaUtilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool areaUtilSpecified {
            get {
                return this.areaUtilFieldSpecified;
            }
            set {
                this.areaUtilFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal areaTotalConstruida {
            get {
                return this.areaTotalConstruidaField;
            }
            set {
                this.areaTotalConstruidaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool areaTotalConstruidaSpecified {
            get {
                return this.areaTotalConstruidaFieldSpecified;
            }
            set {
                this.areaTotalConstruidaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal areaConstruidaPrimerPiso {
            get {
                return this.areaConstruidaPrimerPisoField;
            }
            set {
                this.areaConstruidaPrimerPisoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool areaConstruidaPrimerPisoSpecified {
            get {
                return this.areaConstruidaPrimerPisoFieldSpecified;
            }
            set {
                this.areaConstruidaPrimerPisoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal areaVendibleVivienda {
            get {
                return this.areaVendibleViviendaField;
            }
            set {
                this.areaVendibleViviendaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool areaVendibleViviendaSpecified {
            get {
                return this.areaVendibleViviendaFieldSpecified;
            }
            set {
                this.areaVendibleViviendaFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fna.gov.co/esb/services/bancoproyectos/crearproyectoinmobiliario/v1")]
    public partial class DetalleAreaLote_Crear : DetalleAreaLote {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DetalleAreaConstruccion_Crear))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fna.gov.co/cim/businessentities/detalleareaconstruccion")]
    public partial class DetalleAreaConstruccion {
        
        private decimal areaViviendasField;
        
        private bool areaViviendasFieldSpecified;
        
        private decimal areaCirculacionAbiertaField;
        
        private bool areaCirculacionAbiertaFieldSpecified;
        
        private decimal areaSalonComunalField;
        
        private bool areaSalonComunalFieldSpecified;
        
        private decimal areaPorteriasField;
        
        private bool areaPorteriasFieldSpecified;
        
        private decimal areaComerciosField;
        
        private bool areaComerciosFieldSpecified;
        
        private decimal areaEducacionField;
        
        private bool areaEducacionFieldSpecified;
        
        private decimal areaSaludField;
        
        private bool areaSaludFieldSpecified;
        
        private decimal areaOtrosField;
        
        private bool areaOtrosFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal areaViviendas {
            get {
                return this.areaViviendasField;
            }
            set {
                this.areaViviendasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool areaViviendasSpecified {
            get {
                return this.areaViviendasFieldSpecified;
            }
            set {
                this.areaViviendasFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal areaCirculacionAbierta {
            get {
                return this.areaCirculacionAbiertaField;
            }
            set {
                this.areaCirculacionAbiertaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool areaCirculacionAbiertaSpecified {
            get {
                return this.areaCirculacionAbiertaFieldSpecified;
            }
            set {
                this.areaCirculacionAbiertaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal areaSalonComunal {
            get {
                return this.areaSalonComunalField;
            }
            set {
                this.areaSalonComunalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool areaSalonComunalSpecified {
            get {
                return this.areaSalonComunalFieldSpecified;
            }
            set {
                this.areaSalonComunalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal areaPorterias {
            get {
                return this.areaPorteriasField;
            }
            set {
                this.areaPorteriasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool areaPorteriasSpecified {
            get {
                return this.areaPorteriasFieldSpecified;
            }
            set {
                this.areaPorteriasFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal areaComercios {
            get {
                return this.areaComerciosField;
            }
            set {
                this.areaComerciosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool areaComerciosSpecified {
            get {
                return this.areaComerciosFieldSpecified;
            }
            set {
                this.areaComerciosFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal areaEducacion {
            get {
                return this.areaEducacionField;
            }
            set {
                this.areaEducacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool areaEducacionSpecified {
            get {
                return this.areaEducacionFieldSpecified;
            }
            set {
                this.areaEducacionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal areaSalud {
            get {
                return this.areaSaludField;
            }
            set {
                this.areaSaludField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool areaSaludSpecified {
            get {
                return this.areaSaludFieldSpecified;
            }
            set {
                this.areaSaludFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal areaOtros {
            get {
                return this.areaOtrosField;
            }
            set {
                this.areaOtrosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool areaOtrosSpecified {
            get {
                return this.areaOtrosFieldSpecified;
            }
            set {
                this.areaOtrosFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fna.gov.co/esb/services/bancoproyectos/crearproyectoinmobiliario/v1")]
    public partial class DetalleAreaConstruccion_Crear : DetalleAreaConstruccion {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ClasificacionParqueo_Crear))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fna.gov.co/cim/businessentities/clasificacionparqueo")]
    public partial class ClasificacionParqueo {
        
        private int cantidadPrivadosField;
        
        private bool cantidadPrivadosFieldSpecified;
        
        private int cantidadVisitantesField;
        
        private bool cantidadVisitantesFieldSpecified;
        
        private int cantidadComunalesField;
        
        private bool cantidadComunalesFieldSpecified;
        
        private int cantidadDiscapacitadosField;
        
        private bool cantidadDiscapacitadosFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cantidadPrivados {
            get {
                return this.cantidadPrivadosField;
            }
            set {
                this.cantidadPrivadosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cantidadPrivadosSpecified {
            get {
                return this.cantidadPrivadosFieldSpecified;
            }
            set {
                this.cantidadPrivadosFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cantidadVisitantes {
            get {
                return this.cantidadVisitantesField;
            }
            set {
                this.cantidadVisitantesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cantidadVisitantesSpecified {
            get {
                return this.cantidadVisitantesFieldSpecified;
            }
            set {
                this.cantidadVisitantesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cantidadComunales {
            get {
                return this.cantidadComunalesField;
            }
            set {
                this.cantidadComunalesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cantidadComunalesSpecified {
            get {
                return this.cantidadComunalesFieldSpecified;
            }
            set {
                this.cantidadComunalesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cantidadDiscapacitados {
            get {
                return this.cantidadDiscapacitadosField;
            }
            set {
                this.cantidadDiscapacitadosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cantidadDiscapacitadosSpecified {
            get {
                return this.cantidadDiscapacitadosFieldSpecified;
            }
            set {
                this.cantidadDiscapacitadosFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fna.gov.co/esb/services/bancoproyectos/crearproyectoinmobiliario/v1")]
    public partial class ClasificacionParqueo_Crear : ClasificacionParqueo {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ComposicionGeneralInmobiliario_Crear))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fna.gov.co/cim/businessentities/composiciongeneralinmobiliario")]
    public partial class ComposicionGeneralInmobiliario {
        
        private int cantidadLotesField;
        
        private bool cantidadLotesFieldSpecified;
        
        private int cantidadManzanasField;
        
        private bool cantidadManzanasFieldSpecified;
        
        private int cantidadTorresField;
        
        private bool cantidadTorresFieldSpecified;
        
        private int cantidadBloquesField;
        
        private bool cantidadBloquesFieldSpecified;
        
        private int cantidadPisosField;
        
        private bool cantidadPisosFieldSpecified;
        
        private int cantidadDepositosField;
        
        private bool cantidadDepositosFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cantidadLotes {
            get {
                return this.cantidadLotesField;
            }
            set {
                this.cantidadLotesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cantidadLotesSpecified {
            get {
                return this.cantidadLotesFieldSpecified;
            }
            set {
                this.cantidadLotesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cantidadManzanas {
            get {
                return this.cantidadManzanasField;
            }
            set {
                this.cantidadManzanasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cantidadManzanasSpecified {
            get {
                return this.cantidadManzanasFieldSpecified;
            }
            set {
                this.cantidadManzanasFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cantidadTorres {
            get {
                return this.cantidadTorresField;
            }
            set {
                this.cantidadTorresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cantidadTorresSpecified {
            get {
                return this.cantidadTorresFieldSpecified;
            }
            set {
                this.cantidadTorresFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cantidadBloques {
            get {
                return this.cantidadBloquesField;
            }
            set {
                this.cantidadBloquesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cantidadBloquesSpecified {
            get {
                return this.cantidadBloquesFieldSpecified;
            }
            set {
                this.cantidadBloquesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cantidadPisos {
            get {
                return this.cantidadPisosField;
            }
            set {
                this.cantidadPisosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cantidadPisosSpecified {
            get {
                return this.cantidadPisosFieldSpecified;
            }
            set {
                this.cantidadPisosFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cantidadDepositos {
            get {
                return this.cantidadDepositosField;
            }
            set {
                this.cantidadDepositosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cantidadDepositosSpecified {
            get {
                return this.cantidadDepositosFieldSpecified;
            }
            set {
                this.cantidadDepositosFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fna.gov.co/esb/services/bancoproyectos/crearproyectoinmobiliario/v1")]
    public partial class ComposicionGeneralInmobiliario_Crear : ComposicionGeneralInmobiliario {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ClasificacionInmueble_Crear))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fna.gov.co/cim/businessentities/clasificacioninmueble")]
    public partial class ClasificacionInmueble {
        
        private int cantidadCasasField;
        
        private bool cantidadCasasFieldSpecified;
        
        private int cantidadCasasBifamiliariasField;
        
        private bool cantidadCasasBifamiliariasFieldSpecified;
        
        private int cantidadApartamentosField;
        
        private bool cantidadApartamentosFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cantidadCasas {
            get {
                return this.cantidadCasasField;
            }
            set {
                this.cantidadCasasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cantidadCasasSpecified {
            get {
                return this.cantidadCasasFieldSpecified;
            }
            set {
                this.cantidadCasasFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cantidadCasasBifamiliarias {
            get {
                return this.cantidadCasasBifamiliariasField;
            }
            set {
                this.cantidadCasasBifamiliariasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cantidadCasasBifamiliariasSpecified {
            get {
                return this.cantidadCasasBifamiliariasFieldSpecified;
            }
            set {
                this.cantidadCasasBifamiliariasFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cantidadApartamentos {
            get {
                return this.cantidadApartamentosField;
            }
            set {
                this.cantidadApartamentosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cantidadApartamentosSpecified {
            get {
                return this.cantidadApartamentosFieldSpecified;
            }
            set {
                this.cantidadApartamentosFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fna.gov.co/esb/services/bancoproyectos/crearproyectoinmobiliario/v1")]
    public partial class ClasificacionInmueble_Crear : ClasificacionInmueble {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InventarioViviendas_Crear))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fna.gov.co/cim/businessentities/inventarioviviendas")]
    public partial class InventarioViviendas {
        
        private int viviendasInteresPrioritarioField;
        
        private bool viviendasInteresPrioritarioFieldSpecified;
        
        private int viviendasInteresSocialField;
        
        private bool viviendasInteresSocialFieldSpecified;
        
        private int viviendasInteresNormalField;
        
        private bool viviendasInteresNormalFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int viviendasInteresPrioritario {
            get {
                return this.viviendasInteresPrioritarioField;
            }
            set {
                this.viviendasInteresPrioritarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool viviendasInteresPrioritarioSpecified {
            get {
                return this.viviendasInteresPrioritarioFieldSpecified;
            }
            set {
                this.viviendasInteresPrioritarioFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int viviendasInteresSocial {
            get {
                return this.viviendasInteresSocialField;
            }
            set {
                this.viviendasInteresSocialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool viviendasInteresSocialSpecified {
            get {
                return this.viviendasInteresSocialFieldSpecified;
            }
            set {
                this.viviendasInteresSocialFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int viviendasInteresNormal {
            get {
                return this.viviendasInteresNormalField;
            }
            set {
                this.viviendasInteresNormalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool viviendasInteresNormalSpecified {
            get {
                return this.viviendasInteresNormalFieldSpecified;
            }
            set {
                this.viviendasInteresNormalFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fna.gov.co/esb/services/bancoproyectos/crearproyectoinmobiliario/v1")]
    public partial class InventarioViviendas_Crear : InventarioViviendas {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Telefono_V11))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Telefono_V10))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fna.gov.co/cim/businessentities/telefono")]
    public partial class Telefono {
        
        private string numeroCompletoField;
        
        private string idTelefonoField;
        
        private string tipoTelefonoField;
        
        private string numeroTelefonoField;
        
        private string extensionField;
        
        private int indicativoField;
        
        private bool indicativoFieldSpecified;
        
        private string idDireccionField;
        
        private bool indicadorAutorizacionField;
        
        private bool indicadorAutorizacionFieldSpecified;
        
        private int codigoAreaField;
        
        private bool codigoAreaFieldSpecified;
        
        private int codigoExternoField;
        
        private bool codigoExternoFieldSpecified;
        
        private System.DateTime fechaCreacionField;
        
        private bool fechaCreacionFieldSpecified;
        
        private System.DateTime fechaModificacionField;
        
        private bool fechaModificacionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numeroCompleto {
            get {
                return this.numeroCompletoField;
            }
            set {
                this.numeroCompletoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string idTelefono {
            get {
                return this.idTelefonoField;
            }
            set {
                this.idTelefonoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoTelefono {
            get {
                return this.tipoTelefonoField;
            }
            set {
                this.tipoTelefonoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numeroTelefono {
            get {
                return this.numeroTelefonoField;
            }
            set {
                this.numeroTelefonoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int indicativo {
            get {
                return this.indicativoField;
            }
            set {
                this.indicativoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool indicativoSpecified {
            get {
                return this.indicativoFieldSpecified;
            }
            set {
                this.indicativoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string idDireccion {
            get {
                return this.idDireccionField;
            }
            set {
                this.idDireccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool indicadorAutorizacion {
            get {
                return this.indicadorAutorizacionField;
            }
            set {
                this.indicadorAutorizacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool indicadorAutorizacionSpecified {
            get {
                return this.indicadorAutorizacionFieldSpecified;
            }
            set {
                this.indicadorAutorizacionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigoArea {
            get {
                return this.codigoAreaField;
            }
            set {
                this.codigoAreaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoAreaSpecified {
            get {
                return this.codigoAreaFieldSpecified;
            }
            set {
                this.codigoAreaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigoExterno {
            get {
                return this.codigoExternoField;
            }
            set {
                this.codigoExternoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoExternoSpecified {
            get {
                return this.codigoExternoFieldSpecified;
            }
            set {
                this.codigoExternoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime fechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaCreacionSpecified {
            get {
                return this.fechaCreacionFieldSpecified;
            }
            set {
                this.fechaCreacionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime fechaModificacion {
            get {
                return this.fechaModificacionField;
            }
            set {
                this.fechaModificacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaModificacionSpecified {
            get {
                return this.fechaModificacionFieldSpecified;
            }
            set {
                this.fechaModificacionFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Telefono_V1.1", Namespace="http://www.fna.gov.co/cim/businessentities/telefono")]
    public partial class Telefono_V11 : Telefono {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Telefono_V1.0", Namespace="http://www.fna.gov.co/cim/businessentities/telefono")]
    public partial class Telefono_V10 : Telefono {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DireccionFisica_V21))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DireccionFisica_V20))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DireccionProyecto))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fna.gov.co/cim/businessentities/direccion")]
    public partial class DireccionFisica {
        
        private string idDireccionField;
        
        private string direccionCompletaField;
        
        private string codigoPaisField;
        
        private string nombrePaisField;
        
        private string codigoCiudadField;
        
        private string nombreCiudadField;
        
        private string codigoDepartamentoField;
        
        private string nombreDepartamentoField;
        
        private string codigoCorregimientoField;
        
        private string nombreCorregimientoField;
        
        private string codigoProvinciaField;
        
        private string nombreProvinciaField;
        
        private string tipoDireccionField;
        
        private string codigoSectorField;
        
        private string nombreSectorField;
        
        private string codigoLocalidadField;
        
        private string nombreLocalidadField;
        
        private string codigoBarrioField;
        
        private string nombreBarrioField;
        
        private string nombreUrbanizacionField;
        
        private string estratoField;
        
        private string antiguedadAniosField;
        
        private string antiguedadMesesField;
        
        private string zonaVeredalField;
        
        private string principalField;
        
        private Telefono[] telefonoField;
        
        private int tiempoAnnosField;
        
        private bool tiempoAnnosFieldSpecified;
        
        private int tiempoMesesField;
        
        private bool tiempoMesesFieldSpecified;
        
        private string codigoPostalField;
        
        private string observacionField;
        
        private string codigoPobladoField;
        
        private string nombrePobladoField;
        
        private int codigoExternoField;
        
        private bool codigoExternoFieldSpecified;
        
        private System.DateTime fechaCreacionField;
        
        private bool fechaCreacionFieldSpecified;
        
        private System.DateTime fechaModificacionField;
        
        private bool fechaModificacionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string idDireccion {
            get {
                return this.idDireccionField;
            }
            set {
                this.idDireccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string direccionCompleta {
            get {
                return this.direccionCompletaField;
            }
            set {
                this.direccionCompletaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoPais {
            get {
                return this.codigoPaisField;
            }
            set {
                this.codigoPaisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombrePais {
            get {
                return this.nombrePaisField;
            }
            set {
                this.nombrePaisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoCiudad {
            get {
                return this.codigoCiudadField;
            }
            set {
                this.codigoCiudadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombreCiudad {
            get {
                return this.nombreCiudadField;
            }
            set {
                this.nombreCiudadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoDepartamento {
            get {
                return this.codigoDepartamentoField;
            }
            set {
                this.codigoDepartamentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombreDepartamento {
            get {
                return this.nombreDepartamentoField;
            }
            set {
                this.nombreDepartamentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoCorregimiento {
            get {
                return this.codigoCorregimientoField;
            }
            set {
                this.codigoCorregimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombreCorregimiento {
            get {
                return this.nombreCorregimientoField;
            }
            set {
                this.nombreCorregimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoProvincia {
            get {
                return this.codigoProvinciaField;
            }
            set {
                this.codigoProvinciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombreProvincia {
            get {
                return this.nombreProvinciaField;
            }
            set {
                this.nombreProvinciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoDireccion {
            get {
                return this.tipoDireccionField;
            }
            set {
                this.tipoDireccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoSector {
            get {
                return this.codigoSectorField;
            }
            set {
                this.codigoSectorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombreSector {
            get {
                return this.nombreSectorField;
            }
            set {
                this.nombreSectorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoLocalidad {
            get {
                return this.codigoLocalidadField;
            }
            set {
                this.codigoLocalidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombreLocalidad {
            get {
                return this.nombreLocalidadField;
            }
            set {
                this.nombreLocalidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoBarrio {
            get {
                return this.codigoBarrioField;
            }
            set {
                this.codigoBarrioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombreBarrio {
            get {
                return this.nombreBarrioField;
            }
            set {
                this.nombreBarrioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombreUrbanizacion {
            get {
                return this.nombreUrbanizacionField;
            }
            set {
                this.nombreUrbanizacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estrato {
            get {
                return this.estratoField;
            }
            set {
                this.estratoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string antiguedadAnios {
            get {
                return this.antiguedadAniosField;
            }
            set {
                this.antiguedadAniosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string antiguedadMeses {
            get {
                return this.antiguedadMesesField;
            }
            set {
                this.antiguedadMesesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string zonaVeredal {
            get {
                return this.zonaVeredalField;
            }
            set {
                this.zonaVeredalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string principal {
            get {
                return this.principalField;
            }
            set {
                this.principalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("telefono", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Telefono[] telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int tiempoAnnos {
            get {
                return this.tiempoAnnosField;
            }
            set {
                this.tiempoAnnosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tiempoAnnosSpecified {
            get {
                return this.tiempoAnnosFieldSpecified;
            }
            set {
                this.tiempoAnnosFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int tiempoMeses {
            get {
                return this.tiempoMesesField;
            }
            set {
                this.tiempoMesesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tiempoMesesSpecified {
            get {
                return this.tiempoMesesFieldSpecified;
            }
            set {
                this.tiempoMesesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoPostal {
            get {
                return this.codigoPostalField;
            }
            set {
                this.codigoPostalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string observacion {
            get {
                return this.observacionField;
            }
            set {
                this.observacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoPoblado {
            get {
                return this.codigoPobladoField;
            }
            set {
                this.codigoPobladoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombrePoblado {
            get {
                return this.nombrePobladoField;
            }
            set {
                this.nombrePobladoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigoExterno {
            get {
                return this.codigoExternoField;
            }
            set {
                this.codigoExternoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoExternoSpecified {
            get {
                return this.codigoExternoFieldSpecified;
            }
            set {
                this.codigoExternoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime fechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaCreacionSpecified {
            get {
                return this.fechaCreacionFieldSpecified;
            }
            set {
                this.fechaCreacionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime fechaModificacion {
            get {
                return this.fechaModificacionField;
            }
            set {
                this.fechaModificacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaModificacionSpecified {
            get {
                return this.fechaModificacionFieldSpecified;
            }
            set {
                this.fechaModificacionFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="DireccionFisica_V2.1", Namespace="http://www.fna.gov.co/cim/businessentities/direccion")]
    public partial class DireccionFisica_V21 : DireccionFisica {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="DireccionFisica_V2.0", Namespace="http://www.fna.gov.co/cim/businessentities/direccion")]
    public partial class DireccionFisica_V20 : DireccionFisica {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fna.gov.co/esb/services/bancoproyectos/crearproyectoinmobiliario/v1")]
    public partial class DireccionProyecto : DireccionFisica {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InformacionProyectoInmobiliario_Crear))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fna.gov.co/cim/businessentities/informacionproyectoinmobiliario")]
    public partial class InformacionProyectoInmobiliario {
        
        private string nombreProyectoField;
        
        private int numeroTotalEstructurasField;
        
        private bool numeroTotalEstructurasFieldSpecified;
        
        private int numeroEstructurasFinanciadasField;
        
        private bool numeroEstructurasFinanciadasFieldSpecified;
        
        private string codigoClasificacionProyectoField;
        
        private DireccionFisica direccionField;
        
        private InventarioViviendas inventarioViviendasPorProyectoField;
        
        private ClasificacionInmueble clasificacionInmueblePorProyectoField;
        
        private ComposicionGeneralInmobiliario composicionGeneralProyectoField;
        
        private ClasificacionParqueo clasificacionParqueoProyectoField;
        
        private DetalleAreaConstruccion detalleAreaConstruccionField;
        
        private DetalleAreaLote detalleAreaLoteProyectoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombreProyecto {
            get {
                return this.nombreProyectoField;
            }
            set {
                this.nombreProyectoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int numeroTotalEstructuras {
            get {
                return this.numeroTotalEstructurasField;
            }
            set {
                this.numeroTotalEstructurasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroTotalEstructurasSpecified {
            get {
                return this.numeroTotalEstructurasFieldSpecified;
            }
            set {
                this.numeroTotalEstructurasFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int numeroEstructurasFinanciadas {
            get {
                return this.numeroEstructurasFinanciadasField;
            }
            set {
                this.numeroEstructurasFinanciadasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroEstructurasFinanciadasSpecified {
            get {
                return this.numeroEstructurasFinanciadasFieldSpecified;
            }
            set {
                this.numeroEstructurasFinanciadasFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoClasificacionProyecto {
            get {
                return this.codigoClasificacionProyectoField;
            }
            set {
                this.codigoClasificacionProyectoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DireccionFisica direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InventarioViviendas inventarioViviendasPorProyecto {
            get {
                return this.inventarioViviendasPorProyectoField;
            }
            set {
                this.inventarioViviendasPorProyectoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClasificacionInmueble clasificacionInmueblePorProyecto {
            get {
                return this.clasificacionInmueblePorProyectoField;
            }
            set {
                this.clasificacionInmueblePorProyectoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ComposicionGeneralInmobiliario composicionGeneralProyecto {
            get {
                return this.composicionGeneralProyectoField;
            }
            set {
                this.composicionGeneralProyectoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClasificacionParqueo clasificacionParqueoProyecto {
            get {
                return this.clasificacionParqueoProyectoField;
            }
            set {
                this.clasificacionParqueoProyectoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DetalleAreaConstruccion detalleAreaConstruccion {
            get {
                return this.detalleAreaConstruccionField;
            }
            set {
                this.detalleAreaConstruccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DetalleAreaLote detalleAreaLoteProyecto {
            get {
                return this.detalleAreaLoteProyectoField;
            }
            set {
                this.detalleAreaLoteProyectoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fna.gov.co/esb/services/bancoproyectos/crearproyectoinmobiliario/v1")]
    public partial class InformacionProyectoInmobiliario_Crear : InformacionProyectoInmobiliario {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fna.gov.co/esb/services/bancoproyectos/crearproyectoinmobiliario/v1")]
    public partial class ServiceRequest {
        
        private InformacionProyectoInmobiliario_Crear informacionProyectoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InformacionProyectoInmobiliario_Crear informacionProyecto {
            get {
                return this.informacionProyectoField;
            }
            set {
                this.informacionProyectoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fna.gov.co/esb/services/cl/consumerheader")]
    public partial class Property {
        
        private string keyField;
        
        private string typeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fna.gov.co/esb/services/cl/consumerheader")]
    public partial class Destination {
        
        private string nameField;
        
        private string namespaceField;
        
        private string operationField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="anyURI")]
        public string @namespace {
            get {
                return this.namespaceField;
            }
            set {
                this.namespaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string operation {
            get {
                return this.operationField;
            }
            set {
                this.operationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void CrearProyectoInmobiliarioCompletedEventHandler(object sender, CrearProyectoInmobiliarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CrearProyectoInmobiliarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CrearProyectoInmobiliarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServicioResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServicioResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591